personalQuality = [
'創新概念的形成\n\n為甚麼創意非常重要？\n社會需要創造力 公司需要創造力 個人需要創造力\n\n社會需要創造力 --創造力給社會帶來進步\n公司需要創造力 --創造力為公司帶來盈利\n個人需要創造力 --為個人解決問題',
'創意策略\n不受傳統觀念規限\na.想像－Visualization - 想像和預期理想的完美未來\nb.探索－Exploration - 使用比喻：類比和象徵的手法來質疑假設\nc.組合－Combination - 將各種各樣因素以不同方式結合在一起\nd.修改－Modification - 即興適應，調整已經存在和擁有的。\n',
'衝突的類別\n1.事實之爭\n2.意氣之爭\n3.角色衝突\n4.利益衝突\n5.身份之爭\n6.期望落差\n',
'衝突的類別\n1.<r>事實之爭</r>\n情況:最客觀，最容易解決的一種衝突形態，注意力放了在事物的是是非非上。\n\n處理方法\n例：你認為這是鎚子，他認為這是叉\n方法：衝突雙方尋求一個能共同接受權威的意見。\n\n2.<r>意氣之爭</r>\n情況:這種類型的衝突是主觀和受情緒影響的。\n\n處理方法\n面對這樣的衝突時要緊記『承擔後果』，爭贏了即使可以意氣風發，輸了人際關係卻又不能彌補。\n廣告有話『贏場交，輸頭家，值得嗎?』\n方法：以成熟態度化解爭鬥。\n\n3.<r>角色衝突</r>\n情況:上司和下屬，同行競爭者，情敵…\n\n處理方法\n這是無可避免要發生的事。\n處理這些情況要學習協商，一人行一步，找一個大家可接受的平衡點。坦誠協商，謀求共識。\n\n4.<r>利益衝突</r>\n情況:同事/同業間的競爭，人與人的互相比較，金錢的利益。\n\n處理方法\n為自己著想是人性。\n處理這些情況要學習對事不對人，嘗試合作，協商一個雙贏的方案。\n\n5.<r>身份之爭</r>\n情況:性別歧視，年齡歧視，職位歧視。\n\n處理方法\n解決歧視問題有賴改變觀念，當感到遭受歧視時要提醒自己不要過分敏感。\n\n6.<r>期望落差</r>\n情況:同一情境中各方期望之間的差異\n\n處理方法\n尋求各方共識，以正面情緒處理，理解對方的地位和角色。\n',
'衝突需要時尋找適當的援助\n一、<r>向你的上司反映</r>\n倘若有人與你發生衝突，最佳解決方案多來自自己，別人未必方便/能夠參與。\n但假如衝突損害工作，應向你的上司反映，不然你最後或會被抱怨沒有「及早說出來」\n\n二、<r>徵詢專業的意見</r>\n事實與方法之爭：對於有客觀事實根據的事情，與其發生爭駁，不如及早尋求客觀佐證，或徵詢專業的意見。\n\n三、<r>輔導</r>\n衝突影響情緒：情緒影響你的心理和生理健康，也影響你的工作表現，需要時可找輔導員磋商。\n\n',
'處理衝突的五種策略：\n1.<r>競爭</r>：競爭是一種決勝負的方法；人們通過競爭以決出勝負，勝者為王。\n競爭方式最顯而易見的例子就是競技比賽。\n\n2.<r>妥協</r>：妥協是一種兩敗俱傷的方法。\n各方都同意在同等程度上犧牲各自的需求。\n隨後，又相互達成一項又一項的讓步，最終每方只得到原先所求的一小部分。\n\n3.<r>合作</r>：合作是一種雙贏的方法。\n當採用這種策略時，人們事先同意，直到得出一個能夠滿足各方全部或幾乎全部要求的解決方案，才算完全解決了衝突。\n\n4.<r>觀望</r>：留意事情的發展但不作行動，採用這種策略時，是因為情勢未看清或無把握即時解決。\n\n5.<r>忽略</r>：用於意氣之爭，減少個人對別人反應的過度敏感。\n',
'能力，期望與壓力的關係\n<r>壓力＝期望／要求＞應付能力</r>\n',
'抗壓原動力\n<r>積極</r>：一個人的智慧、體質、經濟和人際關係是抵抗壓力的主要原動力。\n<r>智慧</r>：無論是甚麼困難，都可以用冷靜的頭腦和精密的思維來跨過難關。\n<r>體質</r>：精力旺盛，幹勁十足，即使遇上任何窘境都可支撐下去，更惡劣的環境也奪不去強健的體魄。\n<r>經濟</r>：個人在遇到經濟困難時，能在其支援網內尋找到金錢協助。\n<r>人際</r>：遇困難時，能透過友儕的傾訴和扶持，將負面心境扭轉。\n以上五樣皆你所擁有，你已有充足的抗壓資源面對壓力的挑戰。\n',
'化工作壓力為動力\n一.建立短期/長期目標\n二.多回想過往成功的經驗\n三.每日讓自己進步一些\n四.欣賞自己努力的成果\n',
'客戶服務對營商的重要性\n<r>僱員</r>\n–僱員為接觸顧客的第一員，其表現將直接影響公司的形象，因此僱員是代表公司的。\n\n<r>消費者</r>\n–消費者的口碑可以提高公司的營業額，也可以降低公司的營業額，良好的顧客服務能提高消費者的口碑。\n\n<r>顧客</r>\n–良好的顧客服務可以孕育出忠心的顧客，從而習慣性地使用服務。\n顧客服務可以提高貨品/服務的附加價值，即使較高價錢也會較易令人接受。',
'<r>A.S.K.</r>\n•Attitude 態度\n•Skill 技能\n•Knowledge 知識\n',
'<r>A.S.K.</r>\n\n1.(Attitude)良好對客態度 •誠實可靠 •熱誠有禮 •待人友善 •樂於助人 •有耐心 •體諒顧客 •積極 •主動\n\n2.(Skill)良好服務技能 •整潔儀表 •良好溝通能力 •保持良好顧客關係及促進公司業務之能力\n\n3.(Knowledge)充足的專業知識 •認識貨品/服務 •認識顧客 •了解公司的政策及銷售程序\n',
'<r>內部與外部客人</r>\n何謂顧客？\n\n外在顧客：泛指在工作上我們需要服務的對象\n–公司組織外的顧客。\n–除了商品或服務之使用者或接受者外，還包括經銷商、代理商及零售商等，甚至是流程中的關係或機構。\n\n內在顧客：\n–公司內部的員工\n–工作中與我們工作互動及需要負責的人或部門\n',
'何謂期望落差(Expectation Gap)\n(1)顧客對機構所提供的服務抱有期望\n(2)顧客在接受提供的服務時與期望有分別（落差）\n',
]

improveEnglish = [
'agreed to continue coordinating closely',
'to promote economic, trade, industrial, and energy cooperation between the two countries',
'According to state media',
'highlighted the significant growth in bilateral trade',
'with turnover reaching an estimated USD 2.2 billion',
'marking a nearly 34 percent increase',
'purchase and sale of electricity and mining products',
'shown promising results',
'not only aims to meet needs',
'Bridge Close to Completion\nFriendship Bridge across the River\nlinking Provinces in Laos Thailand\nis now 96 percent complete',
'Lower Inflation in 2024, inflation rate dropped\naccording to official reports\nDespite this decline',
'addresses Illegal Workers Abroad\ngovernment has revealed that some workers are currently working abroad illegally,\nparticularly in neighboring countries,\ndespite the government\'s efforts to create domestic job opportunities',
'held its close-out ceremony today\nThe event recognised the organisation\'s dedication and the contributions it made',
'New Bus Project: A Step Forward or a Traffic Gamble?\ndaily commutes are largely dominated by private vehicles, with public buses playing only a minor role\nHowever, efforts are underway',
'Ends Visa Special Exemption Policy\nhas officially ended its visa exemption and extended stay policy for several countries,\nwhich were specifically introduced during Visit Laos Year\ntourists will need to follow standard visa regulations',
'instructed all immigration checkpoints to revert to pre-2024 visa rules,\nincluding 30-day visas on arrival and embassy-issued visas\nbooked through accredited travel agencies',
'is once again in the spotlight with a fresh tourism draw',
]
