personalQuality = [
'創新概念的形成\n\n為甚麼創意非常重要？\n社會需要創造力 公司需要創造力 個人需要創造力\n\n社會需要創造力 --創造力給社會帶來進步\n公司需要創造力 --創造力為公司帶來盈利\n個人需要創造力 --為個人解決問題',
'創意策略\n不受傳統觀念規限\na.想像－Visualization - 想像和預期理想的完美未來\nb.探索－Exploration - 使用比喻：類比和象徵的手法來質疑假設\nc.組合－Combination - 將各種各樣因素以不同方式結合在一起\nd.修改－Modification - 即興適應，調整已經存在和擁有的。\n',
'衝突的類別\n1.事實之爭\n2.意氣之爭\n3.角色衝突\n4.利益衝突\n5.身份之爭\n6.期望落差\n',
'衝突的類別\n1.<r>事實之爭</r>\n情況:最客觀，最容易解決的一種衝突形態，注意力放了在事物的是是非非上。\n\n處理方法\n例：你認為這是鎚子，他認為這是叉\n方法：衝突雙方尋求一個能共同接受權威的意見。\n\n2.<r>意氣之爭</r>\n情況:這種類型的衝突是主觀和受情緒影響的。\n\n處理方法\n面對這樣的衝突時要緊記『承擔後果』，爭贏了即使可以意氣風發，輸了人際關係卻又不能彌補。\n廣告有話『贏場交，輸頭家，值得嗎?』\n方法：以成熟態度化解爭鬥。\n\n3.<r>角色衝突</r>\n情況:上司和下屬，同行競爭者，情敵…\n\n處理方法\n這是無可避免要發生的事。\n處理這些情況要學習協商，一人行一步，找一個大家可接受的平衡點。坦誠協商，謀求共識。\n\n4.<r>利益衝突</r>\n情況:同事/同業間的競爭，人與人的互相比較，金錢的利益。\n\n處理方法\n為自己著想是人性。\n處理這些情況要學習對事不對人，嘗試合作，協商一個雙贏的方案。\n\n5.<r>身份之爭</r>\n情況:性別歧視，年齡歧視，職位歧視。\n\n處理方法\n解決歧視問題有賴改變觀念，當感到遭受歧視時要提醒自己不要過分敏感。\n\n6.<r>期望落差</r>\n情況:同一情境中各方期望之間的差異\n\n處理方法\n尋求各方共識，以正面情緒處理，理解對方的地位和角色。\n',
'衝突需要時尋找適當的援助\n一、<r>向你的上司反映</r>\n倘若有人與你發生衝突，最佳解決方案多來自自己，別人未必方便/能夠參與。\n但假如衝突損害工作，應向你的上司反映，不然你最後或會被抱怨沒有「及早說出來」\n\n二、<r>徵詢專業的意見</r>\n事實與方法之爭：對於有客觀事實根據的事情，與其發生爭駁，不如及早尋求客觀佐證，或徵詢專業的意見。\n\n三、<r>輔導</r>\n衝突影響情緒：情緒影響你的心理和生理健康，也影響你的工作表現，需要時可找輔導員磋商。\n\n',
'處理衝突的五種策略：\n1.<r>競爭</r>：競爭是一種決勝負的方法；人們通過競爭以決出勝負，勝者為王。\n競爭方式最顯而易見的例子就是競技比賽。\n\n2.<r>妥協</r>：妥協是一種兩敗俱傷的方法。\n各方都同意在同等程度上犧牲各自的需求。\n隨後，又相互達成一項又一項的讓步，最終每方只得到原先所求的一小部分。\n\n3.<r>合作</r>：合作是一種雙贏的方法。\n當採用這種策略時，人們事先同意，直到得出一個能夠滿足各方全部或幾乎全部要求的解決方案，才算完全解決了衝突。\n\n4.<r>觀望</r>：留意事情的發展但不作行動，採用這種策略時，是因為情勢未看清或無把握即時解決。\n\n5.<r>忽略</r>：用於意氣之爭，減少個人對別人反應的過度敏感。\n',
'能力，期望與壓力的關係\n<r>壓力＝期望／要求＞應付能力</r>\n',
'抗壓原動力\n<r>積極</r>：一個人的智慧、體質、經濟和人際關係是抵抗壓力的主要原動力。\n<r>智慧</r>：無論是甚麼困難，都可以用冷靜的頭腦和精密的思維來跨過難關。\n<r>體質</r>：精力旺盛，幹勁十足，即使遇上任何窘境都可支撐下去，更惡劣的環境也奪不去強健的體魄。\n<r>經濟</r>：個人在遇到經濟困難時，能在其支援網內尋找到金錢協助。\n<r>人際</r>：遇困難時，能透過友儕的傾訴和扶持，將負面心境扭轉。\n以上五樣皆你所擁有，你已有充足的抗壓資源面對壓力的挑戰。\n',
'化工作壓力為動力\n一.建立短期/長期目標\n二.多回想過往成功的經驗\n三.每日讓自己進步一些\n四.欣賞自己努力的成果\n',
'客戶服務對營商的重要性\n<r>僱員</r>\n–僱員為接觸顧客的第一員，其表現將直接影響公司的形象，因此僱員是代表公司的。\n\n<r>消費者</r>\n–消費者的口碑可以提高公司的營業額，也可以降低公司的營業額，良好的顧客服務能提高消費者的口碑。\n\n<r>顧客</r>\n–良好的顧客服務可以孕育出忠心的顧客，從而習慣性地使用服務。\n顧客服務可以提高貨品/服務的附加價值，即使較高價錢也會較易令人接受。',
'<r>A.S.K.</r>\n•Attitude 態度\n•Skill 技能\n•Knowledge 知識\n',
'<r>A.S.K.</r>\n\n1.(Attitude)良好對客態度 •誠實可靠 •熱誠有禮 •待人友善 •樂於助人 •有耐心 •體諒顧客 •積極 •主動\n\n2.(Skill)良好服務技能 •整潔儀表 •良好溝通能力 •保持良好顧客關係及促進公司業務之能力\n\n3.(Knowledge)充足的專業知識 •認識貨品/服務 •認識顧客 •了解公司的政策及銷售程序\n',
'<r>內部與外部客人</r>\n何謂顧客？\n\n外在顧客：泛指在工作上我們需要服務的對象\n–公司組織外的顧客。\n–除了商品或服務之使用者或接受者外，還包括經銷商、代理商及零售商等，甚至是流程中的關係或機構。\n\n內在顧客：\n–公司內部的員工\n–工作中與我們工作互動及需要負責的人或部門\n',
'何謂期望落差(Expectation Gap)\n(1)顧客對機構所提供的服務抱有期望\n(2)顧客在接受提供的服務時與期望有分別（落差）\n',
]

improveEnglish = [
'agreed to continue coordinating closely',
'to promote economic, trade, industrial, and energy cooperation between the two countries',
'According to state media',
'highlighted the significant growth in bilateral trade',
'with turnover reaching an estimated USD 2.2 billion',
'marking a nearly 34 percent increase',
'purchase and sale of electricity and mining products',
'shown promising results',
'not only aims to meet needs',
'Bridge Close to Completion\nFriendship Bridge across the River\nlinking Provinces in Laos Thailand\nis now 96 percent complete',
'Lower Inflation in 2024, inflation rate dropped',
'according to official reports',
'Despite this decline',
'addresses Illegal Workers Abroad',
'government has revealed that some workers are currently working abroad illegally,',
'particularly in neighboring countries,',
'despite the government\'s efforts to create domestic job opportunities',
'held its close-out ceremony today',
'The event recognised the organisation\'s dedication and the contributions it made',
'New Bus Project: A Step Forward or a Traffic Gamble?',
'daily commutes are largely dominated by private vehicles, with public buses playing only a minor role',
'However, efforts are underway',
'Ends Visa Special Exemption Policy',
'has officially ended its visa exemption and extended stay policy for several countries',
'which were specifically introduced during Visit Laos Year',
'tourists will need to follow standard visa regulations',
'instructed all immigration checkpoints to revert to pre-2024 visa rules',
'including 30-day visas on arrival and embassy-issued visas',
'booked through accredited travel agencies',
'is once again in the spotlight with a fresh tourism draw',
'Steps Up Fight Against Wildlife Trafficking',
'Authorities continue to intensify efforts against wildlife poaching',
'recent operations leading to the arrest of a suspect',
'a 25-year-old man was apprehended',
'with 10 kilograms of illegal wildlife',
'This latest bust newly exposed the ongoing battle to protect endangered species',
'amidst rising demand for wildlife products in the region',
'keep being closely monitored by authorities',
'uncovered numerous cases of hunting and selling protected species',
'Despite crackdowns the demand for wildlife products continues to threaten biodiversity',
'volatility can change appreciably with time',
'capitalize on these strategic overtures\n利用这些战略提议',
'frames itself as\n将自己定义为',
'goes by “Jerry.”\n叫杰瑞',
'had kind words for historical legacy\n对历史遗产说过好话',
'hardly detectable move toward rebalancing the scales\n难以察觉的平衡天平的变化',
'has ultimately been unable to achieve any results\n最终无法取得任何成果',
'landfall, the landfall facility\n登陆 踏上陆地, 登陆设施',
'lay, laying claim to\n铺设 放置 涂 敷, 声称拥有 要认领',
'long held as, long held as a symbol\n长期以来被认为, 长久以来被视为一种象征',
'lost upwards of 71,000 men\n损失超过71000人',
'made its way to, information made its way to\n到达 传到 流传到, 信息传到了',
'makeover, undergoes major makeover\n翻新 改进 修饰, 进行重大改造',
'malice\n怨恨',
'mandate, base’s mandate\n授权 任期 委托书, 基地的任务',
'mar, marred by violence\n损毁 损伤, 受暴力损毁',
'marquee, the marquee event\n大帐篷 最重要的 最受欢迎的 杰出的, 大型活动',
'Married women of childbearing age 已婚育龄妇女',
'materially benefits\n物质上的好处',
'matter, the problems matter less\n问题 麻烦 物质 材料 东西 命题 事项, 问题不那么重要',
'muck up\n搞砸 弄糟 搞乱',
'muster, muster the will to do it\n集合 召集 集结, 鼓起勇气去做',
'neo-Nazi battalion\n新纳粹营',
'new secular religions\n新兴的世俗宗教',
'no aberration, not an aberration\n无反常现象 无异常行为 无畸变, 不是一种失常',
'No amount of, No amount of negotiating with\n再多也不 即使再大 怎么也 没有数量, 即使再多谈判也不',
'no less a battleground\n就像战场一样 不亚于战场',
'No monkey business\n不要胡闹',
'Non-Aligned Movement\n不结盟运动',
'nonsensical\n无意义的 荒谬的',
'North Pacific Gyre\n北太平洋環流',
'not of a sporadic but of a systemic nature\n不是偶发的，而是系统性的',
'nothing comes from nothing\n无风不起浪',
'notwithstanding, criminal charges notwithstanding, was quite remarkable\n尽管如此 尽管 虽然, 尽管受到刑事指控，但还是很了不起的。',
'nullify, basis for nullifying legal obligations\n使无效 废止 使失去法律效力, 无法律义务的依据',
'obviously disingenuous\n显然是虚伪的',
'OEM\n代加工',
'on and off endeavor\n断断续续的努力',
'on the tarmac\n停机坪上',
'on track, are on track to finish\n在正确的轨道上, 正在顺利完成任务',
'oncology\n肿瘤学',
'One way or another\n无论如何',
'ongoing coup\n正在进行的政变',
'opening-up policies\n对外开放政策',
'osmium\n锇 one of the most scarce elements in the Earth\'s crust',
'ostensibly  表面上 外表 apparently, seemingly, on the face of it',
'outshine, outshine trade route\n出类拔萃 高人一筹 比…做得好, 胜过贸易路线',
'Over-The-Counter\n场外交易的 非挂牌的 非处方的',
'over-the-top, over-the-top results\n超过顶部 过分的, 超一流的结果',
'overture, reached a new overture\n序曲 建议 友好姿态 前奏曲 提议, 达成新的提议',
'pals\n朋友',
'paradoxical statements\n矛盾的语句',
'parallels, The parallels with\n相似特点 媲美, 相似之处',
'passionately called for a breakthrough\n强烈要求取得突破',
'peacekeeping contingent\n维和部队',
'pent-up demand\n被压抑的需求',
'perpetrated by, perpetrated by young males\n犯下, 青年男子所为',
'petty partisanship\n小党派之争',
'phenomenal technology\n非凡的技术',
'phenotypic age\n表型年龄',
'pick-up, toxic pick-up tactics\n提取 搭便车, 有毒的搭便车策略',
'pinky, pinky-promises, pinky white\n小指 廉价葡萄酒, 小指承诺, 本月幸运数字',
'pivot table\n数据分析表',
'plagiarize a line from\n从…剽窃一行',
'pleaded guilty\n承认有罪',
'pledge, graveyard of pledged\n保证 抵押 承诺, 保证墓地',
'plenary session\n全会',
'political awkwardness he endured\n他忍受的政治尴尬',
'postulate, postulated to spread\n假设 假定, 假定传播',
'potential espionage\n潜在的间谍活动',
'pram, out of the pram phase\n婴儿车, 离开婴儿车阶段',
'promptly screwed things up\n很快就把事情搞砸了',
'Province\n起源古罗马的拉丁语 pro-（“代表”）和vincere（“胜利”或“控制”）',
'psycho\n神经病',
'purport, purporting to show\n自称 标榜, 声称显示',
'push people so far\n把人们推得更远',
'quantitative, quantitative basis\n量化的 数量的 定量性的, 定量依据 定量的基础上 量化依据',
'quartet\n四重奏 一套四件',
'radiocarbon dating methods\n放射性碳年代测定法',
'reached the throwing toys\n到了去扔玩具',
'reconcile, reconcile the fact\n妥协 使配合 将就, 妥协事实',
'refused to concede the race\n拒绝比赛认输',
'return on equity\n股本回报率',
'same old same old\n老样子',
'sanctions regime',
'self-referential, self-referential misinformation\n自我参考的, 自我参考的错误信息',
'selling out its farmers in favor of\n出卖农民来支持',
'snake in the grass\n阴险的人 捅刀子的人',
'stifled starry-eyed vision\n扼杀过分乐观的幻想',
'superstructure, coordinated hierarchical superstructure\n上层建筑 上部构造, 协调的分层上层建筑',
'the deck being stacked against them\n对他们不利堆叠的甲板',
'to top it all off\n更有甚者 最妙的是 最糟糕的是',]
