// List of JavaScript tips
var tipsList = [

'onkeydown Event :<br><br>The user pushes a keyboard key\n&lt;input type="text" onkeydown="myFunction()">\n&lt;p id="demo">&lt;/p>\nfunction myFunction() {\n  document.getElementById("demo").innerHTML = "You pressed a key";\n}',
'onload Event :<br><br>The browser has finished loading the page\n&lt;body onload="myFunction()">',
'difference between slice() and substring() :<br><br>substring() cannot accept negative indexes<br>Syntax: string.slice(start, stop);<br>Syntax: string.substring(start, stop);<br><br>Distinctions of substring():<br>If start > stop, then substring will swap those 2 arguments.<br>If either argument is negative or is NaN, it is treated as if it were 0.<br><br>Distinctions of slice():<br>If start > stop, slice() will return the empty string. ("")<br>If start is negative: sets char from the end of string<br>',
'Keywords: continue :<br><br>Jumps out of a loop and starts at the top<br>let text = "";<br><br>for (let i = 0; i < 5; i++) {<br>  if (i === 3) continue;<br>  text += i + "<br>";<br>} // 0 1 2 4<br>',
'Keywords: try ... catch :<br><br>Implements error handling to a block of statements<br>The try statement allows you to define a block of code to be tested for errors.<br>The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.<br>The finally statement lets you execute code, after try and catch, regardless of the result.<br><br>try {<br>  adddlert("Welcome guest!");<br>}<br>catch(err) {<br>  document.getElementById("demo").innerHTML = err.message;<br>}<br>finally {<br>  document.getElementById("demo").value = "";<br>}<br><br>try {<br>  eval("alert(\'Hello)");   // Missing \' will produce an error<br>}<br>catch(err) {<br>  document.getElementById("demo").innerHTML = err.name;<br>}<br>',
':input, eg. $(\":input\") :<br><br>selects All input elements<br>&lt;input type="button" value="Another useless button">&lt;br><br>&lt;input type="reset" value="Reset"><br>&lt;input type="submit" value="Submit">&lt;br><br>\n22 input types:\n"button","checkbox","color","date","datetime-local","email","file","hidden","image","month","number","password","radio","range","reset","search","submit","tel","text","time","url","week"',
'event.which :<br><br>Returns which keyboard key or mouse button was pressed for the event<br>$("input").keydown(function(event){<br>  $("div").html("Key: " + event.which); // 32 for space, 50 for @<br>});<br>',
'prependTo() :<br><br>Inserts HTML elements at the beginning of selected elements<br>$("<span>Hello World!</span>").prependTo("p");',
'map() :<br><br>Passes each element in the matched set through a function, producing a new jQuery object containing the return values<br>Examples<br>const numbers = [4, 9, 16, 25];<br>const newArr = numbers.map(Math.sqrt)<br><br>const numbers = [65, 44, 12, 4];<br>const newArr = numbers.map(myFunction)<br>function myFunction(num) { return num * 10; }<br><br>const persons = [<br>  {firstname : "Malcom", lastname: "Reynolds"},<br>  {firstname : "Kaylee", lastname: "Frye"},<br>  {firstname : "Jayne", lastname: "Cobb"}<br>];<br>persons.map(getFullName);<br>function getFullName(item) { return [item.firstname,item.lastname].join(" "); }',
'$.post() :<br><br>Loads data from a server using an AJAX HTTP POST request<br>$("input").keyup(function(){<br>  var txt = $("input").val();<br>  $.post("demo_ajax_gethint.asp", {suggest: txt}, function(result){<br>    $("span").html(result);<br>  });<br>});<br><br>$("button").click(function(){<br>  $.post("demo_test.asp", function(data, status){<br>    alert("Data: " + data + "\nStatus: " + status);<br>  });<br>});<br>',
'serialize() :<br><br>Encodes a set of form elements as a string for submission<br>$("button").click(function(){<br>  $("div").text($("form").serialize());<br>});<br><br>$.ajax({<br>    type : "POST",<br>    url : "url",<br>    data : $("#form").serialize() + "&par1=1&par2=2&par3=232"<br>}<br>',
'JavaScript Class:<br><br><pre>Use the keyword <i>class</i> to create a class.<br>Always add a method named <i>constructor()</i> to define properties.<br>A JavaScript class is <b>not</b> an object.<br>It is a <b>template</b> for JavaScript objects.<br><br>class Car {<br>   constructor(name, year) {<br>    this.name = name;<br>    this.year = year;<br>  }<br>}<br><br>When you have a class, you can use the class to create objects:<br>let myCar1 = new Car("Ford", 2014);<br>let myCar2 = new Car("Audi", 2019);<br><h3>Class Methods</h3>\n<br>Use the keyword <i>class</i> to create a class.<br>Always add a <i>constructor()</i> method.<br>Then add any number of methods.<br><br>class ClassName {<br>  constructor() { ... }<br>  method_1() { ... }<br>  method_2() { ... }<br>  method_3() { ... }<br>}<br><br>class Car {<br>   constructor(name, year) {<br>    this.name = name;<br>    this.year = year;<br>   }<br>  age() {<br>    let date = new Date();<br>    return date.getFullYear() - this.year;<br>   }<br>}<br><br>let myCar = new Car("Ford", 2014);<br>document.getElementById("demo").innerHTML =<br>"My car is " + myCar.age() + " years old.";</pre>',
'<h2>JavaScript Global Methods and Properties</h2><table>\n<tr><th>Name</th><th>Description</th></tr>\n<tr><td><a href="jsref_decodeuri.asp">decodeURI()</a></td><td>Decodes a URI</td></tr>\n<tr><td><a href="jsref_decodeuricomponent.asp">decodeURI\nComponent()</a></td><td>Decodes a URI component</td></tr>\n<tr><td><a href="jsref_encodeuri.asp">encodeURI()</a></td><td>Encodes a URI</td></tr>\n<tr><td><a href="jsref_encodeuricomponent.asp">encodeURI\nComponent()</a></td><td>Encodes a URI component</td></tr>\n<tr><td><a href="jsref_eval.asp">eval()</a></td><td>Evaluates a string and executes it as if it was script code</td></tr>\n<tr><td><a href="jsref_infinity.asp">Infinity</a></td><td>A numeric value that represents positive/negative infinity</td></tr>\n<tr><td><a href="jsref_isfinite.asp">isFinite()</a></td><td>Determines whether a value is a finite, legal number</td></tr>\n<tr><td><a href="jsref_isnan.asp">isNaN()</a></td><td>Determines whether a value is an illegal number</td></tr>\n<tr><td><a href="jsref_nan.asp">NaN</a></td><td>&quot;Not-a-Number&quot; value</td></tr>\n<tr><td><a href="jsref_number.asp">Number()</a></td><td>Converts an object\'s value to a number</td></tr>\n<tr><td><a href="jsref_parsefloat.asp">parseFloat()</a></td><td>Parses a string and returns a floating point number</td></tr>\n<tr><td><a href="jsref_parseint.asp">parseInt()</a></td><td>Parses a string and returns an integer</td></tr>\n<tr><td><a href="jsref_string.asp">String()</a></td><td>Converts an object\'s value to a string</td></tr>\n<tr><td><a href="jsref_undefined.asp">undefined</a></td><td>Indicates that a variable has not been assigned a value</td></tr>\n<tr><td><a href="jsref_unescape.asp">unescape()</a></td><td><span class="deprecated">Deprecated</span>. Use instead:\n<a href="jsref_decodeuri.asp">decodeURI()</a>\n<a href="jsref_decodeuricomponent.asp">decodeURIComponent()</a></td></tr>\n</table>\n</div>\n<h3>Note</h3>\nSince these methods are global, and global the object is the browser window, these methods are actually window methods:\nisNaN() is the same as window.isNaN().',
'Don\'t forget the var keyword when assigning a variable\'s value for the first time.\nWhen to Use JavaScript var?\nAlways declare JavaScript variables with var, let, or const.\nIf you want your code to run in older browsers, you must use var.',
'undefined, null, 0, false, NaN, and \'\' (empty string) are all falsy.',
'Declare a function with<br/> function <em>myFunctionName</em>() { <br>&nbsp;&nbsp;...<br> }',
'if/else statements look like <br/> if (<em>condition</em>) { <br/>&nbsp;&nbsp;...<br/>} else { <br/>&nbsp;&nbsp;...<br/>}',
'You can return the result of a function into a variable with return:<br><br>function timesFive(inputNumber) {<br> &nbsp;&nbsp;return inputNumber * 5; <br>}<br>console.log(timesFive(6));<br>// Output: 30 ',
'The && operator means both things must be true: <br/>true && true = true<br>true && false = false<br>false && false = false',
'The || operator means either can be true: <br/>true || true = true<br>true || false = true<br>false || false = false',
'A <k>for</k> has three condtions: a start condition, a stop condition, and an iterator: <br><br>for (var i = 0; i < myArray.length; i++) { <br>&nbsp;&nbsp;...<br>}',
'To interpolate a variable into a string, use the + operator, like this: <br><br>var myName = \'Jon\';<br/> \'Hello, my name is \' + myName;',
'To generate a random number, use JavaScript\'s built in function Math.random().',
'Arrays hold lists of data. You can access any of the list items by using bracket notation, like this: <br><br>var myArray = [\'pears\', \'asparagus\', \'bananas\'];<br>myArray[1]; // asparagus',
'jQuery selectors start with the dollar sign and parentheses :<br><br>$()',
'jQuery element selector selects element name :<br><br>$(\'p\'), $(\'div\'), $(\'p\').hide();',
'jQuery #id selector selects the id tag :<br><br>$(\'#test\'),  $(\'#test\').hide();',
'jQuery class selector finds a specific class \'test\' to hide it :<br><br>$(\'.test\').hide();',
'Selects all elements :<br><br>$(\'*\')',
'Selects the current HTML element :<br><br>$(this)',
'Selects all &lt;p&gt; elements with class=\'intro\' :<br><br>$(\'p.intro\')',
'Selects the first &lt;p&gt; element :<br><br>$(\'p:first\')',
'Selects the first &lt;li&gt; element of the first &lt;ul&gt; :<br><br>$(\'ul li:first\')',
'Selects the first &lt;li&gt; element of every &lt;ul&gt; :<br><br>$(\'ul li:first-child\')',
'Selects all elements with an href attribute :<br><br>$(\'[href]\')',
'Selects all &lt;a&gt; elements \"_blank\" :<br><br>$(\'a[target=\'_blank\']\')',
'Selects all &lt;a&gt; elements NOT \"_blank\" :<br><br>$(\'a[target!=\'_blank\']\')',
'Selects all &lt;button&gt; elements and &lt;input&gt; elements of type=\'button\' :<br><br>$(\':button\')',
'Selects all even &lt;tr&gt; elements :<br><br>$(\'tr:even\')',
'Selects all odd &lt;tr&gt; elements in a table :<br><br>$(\'tr:odd\')',
'display data by writing into an HTML element :<br><br>document.getElementById(\"demo\").innerHTML = 5 + 6;',
'display data by writing into the HTML output :<br><br>document.write(5 + 6); will delete all existing HTML',
'display data by writing into an alert box :<br><br>window.alert(5 + 6);',
'display data by writing into the browser console :<br><br>console.log(5 + 6);',
'Javascript Object :<br><br>var car = {type:\"Fiat\', model:\"500\', color:\"white\"};',
'Object Properties :<br><br>The name:values pairs',
'Object Methods :<br><br>Methods are properties stored as function\nconst person = {\n  firstName: "John\',\n  lastName: "Doe\',\n  fullName: function() {\n    return this.firstName + " " + this.lastName;\n  }\n};',
'Object Spaces and line breaks are not important :<br><br>Object definition can span multiple lines',
'Accessing Object Properties :<br><br>objectName.propertyName, or objectName[\"propertyName\"]',
'Accessing Object Methods :<br><br>objectName.methodName(), with ()',
'Local variables have local scope :<br><br>Local scope can only be accessed within the function.',
'Global variable has global scope :<br><br>All scripts and functions on a web page can access global variable',
'Assigning value to a not declared variable :<br><br>Automatically become a GLOBAL variable.',
'onchange Event :<br><br>An HTML element has been changed',
'convert number to string\n\nnum.toString()',
'onclick Event :<br><br>The user clicks an HTML element',
'onmouseover Event :<br><br>The user moves the mouse over an HTML element',
'onmouseout Event :<br><br>The user moves the mouse away from an HTML element',
'String Length Methods :<br><br>var sln = txt.length;',
'String indexOf() method:first occurrence of a specified text :<br><br>var pos = str.indexOf(\"locate\");',
'String lastIndexOf() method:last occurrence of a specified text :<br><br>var pos = str.lastIndexOf(\"locate\");',
'String lastIndexOf() method: accept a second parameter as starting position for the search :<br><br>var pos = str.indexOf(\"locate\',15);',
'String search() method: searches a string :<br><br>str=\"String search() method: searches a string :\"<br><br>pos = str.search(\"method\");',
'String slice() method: extracts a part of a string :<br><br>var res = str.slice(7, 13);',
'String slice() method: negative parameter, counted from the end :<br><br>var res = str.slice(-12, -6);',
'String slice() method: omit the second parameter, slice out the rest :<br><br>var res = str.slice(7);',
'String slice() method: counting from the end :<br><br>var res = str.slice(7);',
'difference between slice() and substr() :<br><br>second parameter specifies the length of the extracted part<br>String.slice( begin, end )<br>String.substr( start, length )<br>',
'replace() method replaces value :<br><br>var n = str.replace(\"Microsoft\', \"W3Schools\");',
'regular expression to replace all matches, with a /g flag :<br><br>var n = str.replace(/Microsoft/g, \"W3Schools\");',
'replace() is case sensitive, To replace case insensitive use /i flag :<br><br>var n = str.replace(/MICROSOFT/i, \"W3Schools\");',
'toUpperCase(): convert to upper case :<br><br>var text2 = text1.toUpperCase();',
'toLowerCase(): convert to lower case :<br><br>var text2 = text1.toLowerCase();',
'concat() joins two or more strings :<br><br>var text3 = text1.concat(\" \', text2);',
'concat() method can use the plus operator :<br><br>var text = \"Hello\" + \" \" + \"World!\";',
'charAt() method returns the character at a specified position :<br><br>str.charAt(0);<br>let text = \'HELLO WORLD\';<br>let letter = text.charAt(1); // E',
'charCodeAt() method returns the unicode of the character at a specified index :<br><br>str.charCodeAt(0);',
'split() method convert string to an array :<br><br>txt.split(\',\"); // Split on commas',
'to end each executable statement :<br><br>Add a semicolon',
'add white space to script to make it more readable :<br><br>JavaScript ignores multiple spaces',
'groupe javaScript statements in code blocks :<br><br>inside curly brackets {...}',
'Keywords: break :<br><br>Terminates a switch or a loop',
'Keywords: debugger :<br><br>Stops the execution and calls the debugging function',
'Keywords: do ... while :<br><br>Executes a block of statements, and repeats while a condition is true',
'Keywords: for :<br><br>Marks block of statements to be executed as long as condition is true',
'Keywords: function :<br><br>Declares a function',
'Keywords: if ... else :<br><br>Marks a block of statements to be executed, depending on condition',
'Keywords: return :<br><br>Exits a function',
'Keywords: switch :<br><br>Marks a block of statements to be executed, depending on different cases',
'Keywords: var :<br><br>Declares a variable',
'<h3>convert a string to a number</h3>\nusing the unary plus operator (+)\nquantity = "12";\n+quantity\n\nconvert array of string to a number\nvar arr = ["1", "2", "3"];\nvar nums = arr.map(unaryOp);\n\n// Function that converts string to number\nfunction unaryOp(value) { return +value; }\n',
'modular operator (%) :<br><br>returns the division remainder. var z = x % y',
'increment operator (++) :<br><br>increments numbers. x++;',
'Exponentiation ** :<br><br>10 ** 2',
'Shift left &lt;&lt; :<br><br>x &lt;&lt; 2',
'Shift right (unsigned) &gt;&gt;&gt; :<br><br>x &gt;&gt;&gt; 2',
'Equal comparator :<br><br>x == y',
'Strict equal :<br><br>x === y',
'Logical and :<br><br>&&',
'Logical or :<br><br>||',
'<h3>jQuery get the image src</h3>$(".class").find("tag").attr("src");',
'Math.PI; :<br><br>returns 3.141592653589793',
'Math.round() :<br><br>Math.round(4.4); returns the value of x rounded to its nearest integer:',
'Math.pow() :<br><br>Math.pow(8, 2); returns the value of x to the power of y:',
'Math.sqrt() :<br><br>Math.sqrt(64);',
'Math.abs() :<br><br>Math.abs(-4.7);',
'Math.ceil() :<br><br>Math.ceil(4.4);',
'Math.floor() :<br><br>Math.floor(4.7);',
'Math.sin() :<br><br>Math.sin(90 * Math.PI / 180);',
'Math.min() :<br><br>Math.min(0, 150, 30, 20, -8, -200);',
'Math.random() :<br><br>Math.random();',
'Math.E :<br><br>returns Euler\'s number',
'Math.SQRT2 :<br><br>returns the square root of 2',
'Math.SQRT1_2 :<br><br>returns the square root of 1/2',
'Math.LN2 :<br><br>returns the natural logarithm of 2',
'Math.LN10 :<br><br>returns the natural logarithm of 10',
'Math.LOG2E :<br><br>returns base 2 logarithm of E',
'Math.LOG10E :<br><br>returns base 10 logarithm of E',
'<k>find unique items in array</k>\nmyArray = ["a", 1, "a", 2, "1"];\nuniqueItems = [...new Set(myArray)]\n["a", 1, 2, "1"]\n',
'abs(x) :<br><br>Returns the absolute value of x',
'acos(x) :<br><br>Returns the arccosine of x, in radians',
'asin(x) :<br><br>Returns the arcsine of x, in radians',
'atan(x) :<br><br>Returns the arctangent of x as a numeric value between -PI/2 and PI/2 radians',
'atan2(y, x) :<br><br>Returns the arctangent of the quotient of its arguments',
'ceil(x) :<br><br>Returns the value of x rounded up to its nearest integer',
'cos(x) :<br><br>Returns the cosine of x (x is in radians)',
'exp(x) :<br><br>Returns the value of Ex',
'floor(x) :<br><br>Returns the value of x rounded down to its nearest integer',
'log(x) :<br><br>Returns the natural logarithm (base E) of x',
'max(x, y, z, ..., n) :<br><br>Returns the number with the highest value',
'min(x, y, z, ..., n) :<br><br>Returns the number with the lowest value',
'pow(x, y) :<br><br>Returns the value of x to the power of y',
'random() :<br><br>Returns a random number between 0 and 1',
'round(x) :<br><br>Returns the value of x rounded to its nearest integer',
'sin(x) :<br><br>Returns the sine of x (x is in radians)',
'sqrt(x) :<br><br>Returns the square root of x',
'tan(x) :<br><br>Returns the tangent of an angle',
'Math.random() :<br><br>returns a random number between 0 (inclusive),  and 1 (exclusive) Math.random();',
'Random Integers :<br><br>Math.floor(Math.random() * 10);',
'Displaying Dates :<br><br>document.getElementById(\"demo\").innerHTML = Date();',
'Creating Date Objects :<br><br>new Date(dateString), Date(milliseconds)',
'date object from the specified date and time :<br><br>var d = new Date(\"October 13, 2014 11:13:00\");',
'HTML onclick event :<br><br>In HTML: &lt;element onclick=\"myScript\"&gt;',
'JavaScript onclick function :<br><br>In JavaScript: object.onclick = function(){myScript};',
'JavaScript onclick using the addEventListener() method :<br><br>object.addEventListener(\"click\', myScript);',
'JavaScript onclick object example :<br><br>document.getElementById(\"demo\").onclick = function() {myFunction()};',
'HTML set object content :<br><br>document.getElementById(\"demo\").innerHTML = \"Changed!\";',
'JavaScript prompt for input :<br><br>var person = prompt(\"Please enter your name\', \"Harry Potter\");',
'JavaScript concat strings :<br><br>\"Hello \" + person + \"! How are you?\";',
'JavaScript Display an alert box :<br><br>alert(\"Hello! I am an alert box!!\");',
'HTML DOM writeln() Method :<br><br>document.writeln(\'Hello there!\');',
'HTML DOM writeln with attributes :<br><br>document.writeln(\'&lt;font face=\"Arial\" size=\"5\" color=\"red\"&gt;Hello there!&lt;/font&gt;\');',
'HTML opening a new window :<br><br>&lt;a href=\"link.html\" target=\"_blank\"&gt;Click Here&lt;/a&gt;',
'HTML opening a new window with name :<br><br>&lt;a href=\"link.html\" target=\"mywindow\"&gt;Click Here&lt;/a&gt;',
'JavaScript Opening A Window :<br><br>window.open(\'link.html\',\'mywindow\');',
'JavaScript onclick Opening A Window :<br><br>&lt;a href=\"#\" onClick=\"window.open(\'link.html\',\'mywindow\');\"&gt;Click Here&lt;/a&gt;',
'JavaScript window.open set window features :<br><br>window.open(\'link.html\',\'mywindow\',\'window features\');',
'JavaScript window.open location bar and status bar :<br><br>window.open(\'link.html\',\'mywindow\',\'location, status\');',
'JavaScript window.open Features :<br><br>menubar, scrollbar, width, height, toolbar, location, resizable, directories',
'JavaScript window.open Features sample :<br><br>window.open(\'window1.htm\',\'newwindow\',\'height=300,width=200,status,scrollbars\');',
'Javascript Link Events :<br><br>including JavaScript without &lt;script&gt; tags in HTML',
'Javascript Link Events execute when certain things happen :<br><br>&lt;a href=\"#\" onClick=\"JavaScript Code\"&gt;Click Here&lt;/a&gt;',
'three ways of executing Link Events :<br><br>onClick, onMouseOver, onMouseOut',
'Link Events for image swaps (mouseover images) :<br><br>&lt;a href=\"index.htm\" onMouseOver=\"button.src=\'homeon.gif\';\" onMouseOut=\"button.src=\'home.gif\';\"&gt;&lt;img src=\"home.gif\" name=\"button\"&gt;&lt;/a&gt;',
'No id name &lt;a href=\"#\"&gt;Click Here&lt;/a&gt; :<br><br>specify the top position',
'JavaScript Link Events for Status Bar text :<br><br>window.status=\'Your Text In Here\';',
'Two JavaScripts most important functions :<br><br>If and Loops',
'JavaScript if function :<br><br>if(guess == 5){}',
'JavaScript while function :<br><br>while(input != password){}',
'JavaScript for function :<br><br>for(loop=0; loop &lt; 11; loop++){}',
'HTML create a form :<br><br>&lt;form name=\"formname\"&gt;&lt;/form&gt;',
'HTML Place a text box :<br><br>&lt;input type=\"text\" name=\"boxname\"&gt;',
'set object value :<br><br>window.document.formname.first_text.value=\'Hi there\';',
'JavaScript onBlur Event :<br><br>cursor leaves an input field &lt;input type=\"text\" onblur=\"myFunction()\"&gt;',
'JavaScript onFocus Event :<br><br>cursor is moved into the field &lt;input type=\"text\" onfocus=\"myFunction()\"&gt;',
'JavaScript onchange Event :<br><br>the field is changed and the cursor moves out of it object.onchange = function(){myScript};',
'JavaScript onMouseOver sample :<br><br>&lt;a href=\"#\" onMouseOver=\"sayhi();\"&gt;Say Hi&lt;/a&gt;',
'JavaScript Submit Button :<br><br>&lt;form name=\"myform\" onSubmit=\"MyFunction();&gt;',
'Two form items :<br><br>Checkboxes and radio buttons',
'to check Checkboxes :<br><br>if(window.document.example1.my_checkbox.checked=true){}',
'JavaScript Switch Statement :<br><br>switch(expression) {case n: ... break; default: ... }',
'JavaScript For/In Loop :<br><br>for (x in person) {}',
'JavaScript Break :<br><br>for (i = 0; i &lt; 10; i++) {if (i === 3) { break; }}',
'JavaScript Continue :<br><br>for (i = 0; i &lt; 10; i++) {if (i === 3) { continue; }}',
'JavaScript Labels :<br><br>label: ... break labelname; continue labelname;',
'JavaScript open window and write content :<br><br>var imgWindow = window.open(\"\"); imgWindow.document.write(theListDom);',
'JavaScript history.back function :<br><br>$(\'.keys\').click(function(){parent.history.back();}',
'Jquery load file :<br><br>$.get(\'5FC.txt\', function (d) {var theList = d.split(\',\');}',
'object.append :<br><br>$( \"#codelist\" ).append(\"Total: \" + theList.length + \"&lt;br&gt;\");',
'Jquery getChar(event) :<br><br>{return String.fromCharCode(event.which)}',
'Jquery chkKey() :<br><br>var testkey = getChar(event); if(testkey == \'9\'){...}',
'JavaScript window.scrollTo :<br><br>&lt;b class=\"left\" onclick=\"window.scrollTo(0,document.body.scrollHeight);\"&gt;Go Bottom&lt;/b&gt;',
'The JavaScript labeled statement can be used with... :<br><br>break or continue statements, useful in nested loops (loops inside loops)',
'JavaScript Form submit() Method :<br><br>Submit a form: document.getElementById(\"myForm\").submit();',
'load jquery script :<br><br>&lt;script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.js\"&gt;&lt;/script&gt;',
'define an empty object :<br><br>&lt;div id=\"toc\"&gt;&lt;/div&gt;',
'assign an empty object to a variable :<br><br>var toc = $(\'#toc\');',
'a makeLine function to create HTML lines :<br><br>function makeLi(text, href) {return $(\'&lt;a href=\"\' + href + \'\"&gt;\' + text + \'&lt;/a&gt;&lt;br&gt;\');}',
'Jquery each function :<br><br>$(\'h1, h2\').each(function(i) {...}',
'Jquery this selector :<br><br>Selects the current HTML element',
'Jquery this selector sample :<br><br>var chapter = $(this), chapterNumber = i + 1;',
'Javascript append method :<br><br>toc.append(makeLi(\'Chapter \' + chapterNumber + \': \' + chapter.text(), \'#chapter-\' + chapterNumber));',
'jQuery attr() Method :<br><br>chapter.attr(\'id\', \'chapter-\' + chapterNumber);',
'jQuery prepend() Method :<br><br>chapter.prepend(\'&lt;p class=\"toc\"&gt;&lt;a title=\"Back to top\" href=\"#toc\"&gt;Top&lt;/a&gt;&lt;/p&gt;\');',
'$(\"*\") :<br><br>Jquery Selects all elements',
'$(this) :<br><br>Jquery Selects the current HTML element',
'$(\"p.intro\") :<br><br>Jquery Selects all &lt;p&gt; elements with class=\"intro\"',
'$(\"p:first\") :<br><br>Jquery Selects the first &lt;p&gt; element',
'$(\"ul li:first\") :<br><br>Jquery Selects the first &lt;li&gt; element of the first &lt;ul&gt;',
'$(\"ul li:first-child\") :<br><br>Jquery Selects the first &lt;li&gt; element of every &lt;ul&gt;',
'$(\"[href]\") :<br><br>Jquery Selects all elements with an href attribute',
'$(\"a[target=\'_blank\']\") :<br><br>Jquery Selects all &lt;a&gt; elements with a target attribute value equal to \"_blank\"',
'$(\"a[target!=\'_blank\']\") :<br><br>Jquery Selects all &lt;a&gt; elements with a target attribute value NOT equal to \"_blank\"',
'$(\":button\") :<br><br>Jquery Selects all &lt;button&gt; elements and &lt;input&gt; elements of type=\"button\"',
'$(\"tr:even\") :<br><br>Jquery Selects all even &lt;tr&gt; elements',
'$(\"tr:odd\") :<br><br>Jquery Selects all odd &lt;tr&gt; elements',
'*, eg. $(\"*\") :<br><br>selects All elements',
'#id, eg. $(\"#lastname\") :<br><br>selects The element with id=\"lastname\"',
'.class, eg. $(\".intro\") :<br><br>selects All elements with class=\"intro\"',
'.class,.class, eg. $(\".intro,.demo\") :<br><br>selects All elements with the class \"intro\" or \"demo\"',
'element, eg. $(\"p\") :<br><br>selects All &lt;p&gt; elements',
'el1, el2, el3, eg. $(\"h1,div,p\") :<br><br>selects All &lt;h1&gt;, &lt;div&gt; and &lt;p&gt; elements',
':first, eg. $(\"p:first\") :<br><br>selects The first &lt;p&gt; element',
':last, eg. $(\"p:last\") :<br><br>selects The last &lt;p&gt; element',
':even, eg. $(\"tr:even\") :<br><br>selects All even &lt;tr&gt; elements',
':odd, eg. $(\"tr:odd\") :<br><br>selects All odd &lt;tr&gt; elements',
':first-child, eg. $(\"p:first-child\") :<br><br>selects All &lt;p&gt; elements that are the first child of their parent',
':first-of-type, eg. $(\"p:first-of-type\") :<br><br>selects All &lt;p&gt; elements that are the first &lt;p&gt; element of their parent',
':last-child, eg. $(\"p:last-child\") :<br><br>selects All &lt;p&gt; elements that are the last child of their parent',
':last-of-type, eg. $(\"p:last-of-type\") :<br><br>selects All &lt;p&gt; elements that are the last &lt;p&gt; element of their parent',
':nth-child(n), eg. $(\"p:nth-child(2)\") :<br><br>selects All &lt;p&gt; elements that are the 2nd child of their parent',
':nth-last-child(n), eg. $(\"p:nth-last-child(2)\") :<br><br>selects All &lt;p&gt; elements that are the 2nd child of their parent, counting from the last child',
':nth-of-type(n), eg. $(\"p:nth-of-type(2)\") :<br><br>selects All &lt;p&gt; elements that are the 2nd &lt;p&gt; element of their parent',
':nth-last-of-type(n), eg. $(\"p:nth-last-of-type(2)\") :<br><br>selects All &lt;p&gt; elements that are the 2nd &lt;p&gt; element of their parent, counting from the last child',
':only-child, eg. $(\"p:only-child\") :<br><br>selects All &lt;p&gt; elements that are the only child of their parent',
':only-of-type, eg. $(\"p:only-of-type\") :<br><br>selects All &lt;p&gt; elements that are the only child, of its type, of their parent<br>element that has no siblings of the given type<br>li:only-of-type { color: red; }<br>&lt;ul> &lt;li>I\'m all alone!&lt;/li> &lt;/ul>  // this is red<br>&lt;ul><br>  &lt;li>We are together.&lt;/li><br>  &lt;li>We are together.&lt;/li><br>  &lt;li>We are together.&lt;/li><br>&lt;/ul>  <br>',
'parent &gt; child, eg. $(\"div &gt; p\") :<br><br>selects All &lt;p&gt; elements that are a direct child of a &lt;div&gt; element',
'parent descendant, eg. $(\"div p\") :<br><br>selects All &lt;p&gt; elements that are descendants of a &lt;div&gt; element',
'element + next, eg. $(\"div + p\") :<br><br>selects The &lt;p&gt; element that are next to each &lt;div&gt; elements',
'element ~ siblings, eg. $(\"div ~ p\") :<br><br>selects All &lt;p&gt; elements that are siblings of a &lt;div&gt; element',
':eq(index), eg. $(\"ul li:eq(3)\") :<br><br>selects The fourth element in a list (index starts at 0)',
':gt(no), eg. $(\"ul li:gt(3)\") :<br><br>selects List elements with an index greater than 3',
':lt(no), eg. $(\"ul li:lt(3)\") :<br><br>selects List elements with an index less than 3',
':not(selector), eg. $(\"input:not(:empty)\") :<br><br>selects All input elements that are not empty',
':header, eg. $(\":header\") :<br><br>selects All header elements &lt;h1&gt;, &lt;h2&gt; ...',
':animated, eg. $(\":animated\") :<br><br>selects All animated elements',
':focus, eg. $(\":focus\") :<br><br>selects The element that currently has focus',
':contains(text), eg. $(\":contains(\'Hello\')\") :<br><br>selects All elements which contains the text \"Hello\"',
':has(selector), eg. $(\"div:has(p)\") :<br><br>selects All &lt;div&gt; elements that have a &lt;p&gt; element',
':empty, eg. $(\":empty\") :<br><br>selects All elements that are empty',
':parent, eg. $(\":parent\") :<br><br>selects All elements that are a parent of another element',
':hidden, eg. $(\"p:hidden\") :<br><br>selects All hidden &lt;p&gt; elements',
':visible, eg. $(\"table:visible\") :<br><br>selects All visible tables',
':root, eg. $(\":root\") :<br><br>selects The document\'s root element',
':lang(language), eg. $(\"p:lang(de)\") :<br><br>selects All &lt;p&gt; elements with a lang attribute value starting with \"de\"',
'[attribute], eg. $(\"[href]\") :<br><br>selects All elements with a href attribute',
'[attribute=value], eg. $(\"[href=\'default.htm\']\") :<br><br>selects All elements with a href attribute value equal to \"default.htm\"',
'[attribute!=value], eg. $(\"[href!=\'default.htm\']\") :<br><br>selects All elements with a href attribute value not equal to \"default.htm\"',
'[attribute$=value], eg. $(\"[href$=\'.jpg\']\") :<br><br>selects All elements with a href attribute value ending with \".jpg\"',
'[attribute|=value], eg. $(\"[title|=\'Tomorrow\']\") :<br><br>selects All elements with a title attribute value equal to \'Tomorrow\', or starting with \'Tomorrow\' followed by a hyphen',
'[attribute^=value], eg. $(\"[title^=\'Tom\']\") :<br><br>selects All elements with a title attribute value starting with \"Tom\"',
'[attribute~=value], eg. $(\"[title~=\'hello\']\") :<br><br>selects All elements with a title attribute value containing the specific word \"hello\"',
'[attribute*=value], eg. $(\"[title*=\'hello\']\") :<br><br>selects All elements with a title attribute value containing the word \"hello\"',
':text, eg. $(\":text\") :<br><br>selects All input elements with type=\"text\"',
':password, eg. $(\":password\") :<br><br>selects All input elements with type=\"password\"',
':radio, eg. $(\":radio\") :<br><br>selects All input elements with type=\"radio\"',
':checkbox, eg. $(\":checkbox\") :<br><br>selects All input elements with type=\"checkbox\"',
':submit, eg. $(\":submit\") :<br><br>selects All input elements with type=\"submit\"',
':reset, eg. $(\":reset\") :<br><br>selects All input elements with type=\"reset\"',
':button, eg. $(\":button\") :<br><br>selects All input elements with type=\"button\"',
':image, eg. $(\":image\") :<br><br>selects All input elements with type=\"image\"',
':file, eg. $(\":file\") :<br><br>selects All input elements with type=\"file\"',
':enabled, eg. $(\":enabled\") :<br><br>selects All enabled input elements',
':disabled, eg. $(\":disabled\") :<br><br>selects All disabled input elements',
':selected, eg. $(\":selected\") :<br><br>selects All selected input elements',
':checked, eg. $(\":checked\") :<br><br>selects All checked input elements',
'blur() :<br><br>Attaches/Triggers the blur event',
'change() :<br><br>Attaches/Triggers the change event',
'click() :<br><br>Attaches/Triggers the click event',
'dblclick() :<br><br>Attaches/Triggers the double click event',
'die() :<br><br>Removed in version 1.9. Removes all event handlers added with the live() method',
'event.currentTarget :<br><br>The current DOM element within the event bubbling phase',
'event.data :<br><br>Contains the optional data passed to an event method when the current executing handler is bound',
'event.delegateTarget :<br><br>Returns the element where the currently-called jQuery event handler was attached',
'event.isDefaultPrevented() :<br><br>Returns whether event.preventDefault() was called for the event object',
'event.isImmediatePropagationStopped() :<br><br>Returns whether event.stopImmediatePropagation() was called for the event object',
'event.isPropagationStopped() :<br><br>Returns whether event.stopPropagation() was called for the event object',
'event.namespace :<br><br>Returns the namespace specified when the event was triggered',
'event.pageX :<br><br>Returns the mouse position relative to the left edge of the document',
'event.pageY :<br><br>Returns the mouse position relative to the top edge of the document',
'event.preventDefault() :<br><br>Prevents the default action of the event',
'event.relatedTarget :<br><br>Returns which element being entered or exited on mouse movement.',
'event.result :<br><br>Contains the last/previous value returned by an event handler triggered by the specified event',
'event.stopImmediatePropagation() :<br><br>Prevents other event handlers from being called',
'event.stopPropagation() :<br><br>Prevents the event from bubbling up the DOM tree, preventing any parent handlers from being notified of the event',
'event.target :<br><br>Returns which DOM element triggered the event',
'event.timeStamp :<br><br>Returns the number of milliseconds since January 1, 1970, when the event is triggered',
'event.type :<br><br>Returns which event type was triggered',
'focus() :<br><br>Attaches/Triggers the focus event',
'focusin() :<br><br>Attaches an event handler to the focusin event',
'focusout() :<br><br>Attaches an event handler to the focusout event',
'hover() :<br><br>Attaches two event handlers to the hover event',
'keydown() :<br><br>Attaches/Triggers the keydown event',
'keypress() :<br><br>Attaches/Triggers the keypress event',
'keyup() :<br><br>Attaches/Triggers the keyup event',
'live() :<br><br>Removed in version 1.9. Adds one or more event handlers to current, or future, selected elements',
'mousedown() :<br><br>Attaches/Triggers the mousedown event',
'mouseenter() :<br><br>Attaches/Triggers the mouseenter event',
'mouseleave() :<br><br>Attaches/Triggers the mouseleave event',
'mousemove() :<br><br>Attaches/Triggers the mousemove event',
'mouseout() :<br><br>Attaches/Triggers the mouseout event',
'mouseover() :<br><br>Attaches/Triggers the mouseover event',
'mouseup() :<br><br>Attaches/Triggers the mouseup event',
'off() :<br><br>Removes event handlers attached with the on() method',
'on() :<br><br>Attaches event handlers to elements',
'one() :<br><br>Adds one or more event handlers to selected elements. This handler can only be triggered once per element',
'$.proxy() :<br><br>Takes an existing function and returns a new one with a particular context',
'ready() :<br><br>Specifies a function to execute when the DOM is fully loaded',
'resize() :<br><br>Attaches/Triggers the resize event',
'scroll() :<br><br>Attaches/Triggers the scroll event',
'select() :<br><br>Attaches/Triggers the select event',
'submit() :<br><br>Attaches/Triggers the submit event',
'toggle() :<br><br>Removed in version 1.9. Attaches two or more functions to toggle between for the click event',
'trigger() :<br><br>Triggers all events bound to the selected elements',
'triggerHandler() :<br><br>Triggers all functions bound to a specified event for the selected elements',
'animate() :<br><br>Runs a custom animation on the selected elements',
'clearQueue() :<br><br>Removes all remaining queued functions from the selected elements',
'delay() :<br><br>Sets a delay for all queued functions on the selected elements<br>$(\'button\').click(function(){<br>  $(\'#div1\').delay(\'slow\').fadeIn();<br>  $(\'#div2\').delay(\'fast\').fadeIn();<br>});<br><br>var delayInMilliseconds = 1000; //1 second<br>setTimeout(function() {<br>  //your code to be executed after 1 second<br>}, delayInMilliseconds);<br>',
'dequeue() :<br><br>Removes the next function from the queue, and then executes the function',
'fadeIn() :<br><br>Fades in the selected elements',
'fadeOut() :<br><br>Fades out the selected elements',
'fadeTo() :<br><br>Fades in/out the selected elements to a given opacity',
'fadeToggle() :<br><br>Toggles between the fadeIn() and fadeOut() methods',
'finish() :<br><br>Stops, removes and completes all queued animations for the selected elements',
'hide() :<br><br>Hides the selected elements',
'queue() :<br><br>Shows the queued functions on the selected elements',
'show() :<br><br>Shows the selected elements',
'slideDown() :<br><br>Slides-down (shows) the selected elements',
'slideToggle() :<br><br>Toggles between the slideUp() and slideDown() methods',
'slideUp() :<br><br>Slides-up (hides) the selected elements',
'stop() :<br><br>Stops the currently running animation for the selected elements',
'toggle() :<br><br>Toggles between the hide() and show() methods',
'addClass() :<br><br>Adds one or more class names to selected elements',
'after() :<br><br>Inserts content after selected elements',
'append() :<br><br>Inserts content at the end of selected elements',
'appendTo() :<br><br>Inserts HTML elements at the end of selected elements',
'attr() :<br><br>Sets or returns attributes/values of selected elements',
'before() :<br><br>Inserts content before selected elements',
'clone() :<br><br>Makes a copy of selected elements',
'css() :<br><br>Sets or returns one or more style properties for selected elements',
'detach() :<br><br>Removes selected elements (keeps data and events)',
'empty() :<br><br>Removes all child nodes and content from selected elements',
'hasClass() :<br><br>Checks if any of the selected elements have a specified class name',
'height() :<br><br>Sets or returns the height of selected elements',
'html() :<br><br>Sets or returns the content of selected elements',
'innerHeight() :<br><br>Returns the height of an element (includes padding, but not border)',
'innerWidth() :<br><br>Returns the width of an element (includes padding, but not border)',
'insertAfter() :<br><br>Inserts HTML elements after selected elements',
'insertBefore() :<br><br>Inserts HTML elements before selected elements',
'offset() :<br><br>Sets or returns the offset coordinates for selected elements (relative to the document)',
'offsetParent() :<br><br>Returns the first positioned parent element',
'outerHeight() :<br><br>Returns the height of an element (includes padding and border)',
'outerWidth() :<br><br>Returns the width of an element (includes padding and border)',
'position() :<br><br>Returns the position (relative to the parent element) of an element',
'prepend() :<br><br>Inserts content at the beginning of selected elements',
'prop() :<br><br>Sets or returns properties/values of selected elements',
'remove() :<br><br>Removes the selected elements (including data and events)',
'removeAttr() :<br><br>Removes one or more attributes from selected elements',
'removeClass() :<br><br>Removes one or more classes from selected elements',
'removeProp() :<br><br>Removes a property set by the prop() method',
'replaceAll() :<br><br>Replaces selected elements with new HTML elements',
'replaceWith() :<br><br>Replaces selected elements with new content',
'scrollLeft() :<br><br>Sets or returns the horizontal scrollbar position of selected elements',
'scrollTop() :<br><br>Sets or returns the vertical scrollbar position of selected elements',
'text() :<br><br>Sets or returns the text content of selected elements',
'toggleClass() :<br><br>Toggles between adding/removing one or more classes from selected elements',
'unwrap() :<br><br>Removes the parent element of the selected elements',
'val() :<br><br>Sets or returns the value attribute of the selected elements (for form elements)',
'width() :<br><br>Sets or returns the width of selected elements',
'wrap() :<br><br>Wraps HTML element(s) around each selected element',
'wrapAll() :<br><br>Wraps HTML element(s) around all selected elements',
'wrapInner() :<br><br>Wraps HTML element(s) around the content of each selected element',
'add() :<br><br>Adds elements to the set of matched elements',
'addBack() :<br><br>Adds the previous set of elements to the current set',
'children() :<br><br>Returns all direct children of the selected element',
'closest() :<br><br>Returns the first ancestor of the selected element',
'contents() :<br><br>Returns all direct children of the selected element (including text and comment nodes)',
'each() :<br><br>Executes a function for each matched element',
'end() :<br><br>Ends the most recent filtering operation in the current chain, and return the set of matched elements to its previous state',
'eq() :<br><br>Returns an element with a specific index number of the selected elements',
'filter() :<br><br>Reduce the set of matched elements to those that match the selector or pass the function\'s test',
'find() :<br><br>Returns descendant elements of the selected element',
'first() :<br><br>Returns the first element of the selected elements',
'has() :<br><br>Returns all elements that have one or more elements inside of them',
'is() :<br><br>Checks the set of matched elements against a selector/element/jQuery object, and return true if at least one of these elements matches the given arguments',
'last() :<br><br>Returns the last element of the selected elements',
'next() :<br><br>Returns the next sibling element of the selected element',
'nextAll() :<br><br>Returns all next sibling elements of the selected element',
'nextUntil() :<br><br>Returns all next sibling elements between two given arguments',
'not() :<br><br>Remove elements from the set of matched elements',
'offsetParent() :<br><br>Returns the first positioned parent element',
'parent() :<br><br>Returns the direct parent element of the selected element',
'parents() :<br><br>Returns all ancestor elements of the selected element',
'parentsUntil() :<br><br>Returns all ancestor elements between two given arguments',
'prev() :<br><br>Returns the previous sibling element of the selected element<br>$( \'li.third-item\' ).prev().css( \'background-color\', \'red\' );',
'prevAll() :<br><br>Returns all previous sibling elements of the selected element',
'prevUntil() :<br><br>Returns all previous sibling elements between two given arguments',
'siblings() :<br><br>Returns all sibling elements of the selected element',
'slice() :<br><br>Reduces the set of matched elements to a subset specified by a range of indices',
'$.ajax() :<br><br>Performs an async AJAX request',
'$.ajaxPrefilter() :<br><br>Handle custom Ajax options or modify existing options before each request is sent and before they are processed by $.ajax()',
'$.ajaxSetup() :<br><br>Sets the default values for future AJAX requests',
'$.ajaxTransport() :<br><br>Creates an object that handles the actual transmission of Ajax data',
'$.getJSON() :<br><br>Loads JSON-encoded data from a server using a HTTP GET request',
'$.getScript() :<br><br>Loads (and executes) a JavaScript from a server using an AJAX HTTP GET request',
'$.param() :<br><br>Creates a serialized representation of an array or object (can be used as URL query string for AJAX requests)',
'ajaxComplete() :<br><br>Specifies a function to run when the AJAX request completes',
'ajaxError() :<br><br>Specifies a function to run when the AJAX request completes with an error',
'ajaxSend() :<br><br>Specifies a function to run before the AJAX request is sent',
'ajaxStart() :<br><br>Specifies a function to run when the first AJAX request begins',
'ajaxStop() :<br><br>Specifies a function to run when all AJAX requests have completed',
'ajaxSuccess() :<br><br>Specifies a function to run when an AJAX request completes successfully',
'load() :<br><br>Loads data from a server and puts the returned data into the selected element',
'serializeArray() :<br><br>Encodes a set of form elements as an array of names and values',
'data() :<br><br>Attaches data to, or gets data from, selected elements',
'each() :<br><br>Execute a function for each matched element',
'get() :<br><br>Get the DOM elements matched by the selector',
'index() :<br><br>Search for a given element from among the matched elements',
'$.noConflict() :<br><br>Release jQuery\'s control of the $ variable',
'$.param() :<br><br>Create a serialized representation of an array or object (can be used as URL query string for AJAX requests)',
'removeData() :<br><br>Removes a previously-stored piece of data',
'toArray() :<br><br>Retrieve all the DOM elements contained in the jQuery set, as an array',
'jquery :<br><br>Contains the jQuery version number',
'jQuery.fx.interval :<br><br>Change the animation firing rate in milliseconds',
'jQuery.fx.off :<br><br>Globally disable/enable all animations',
'jQuery.support :<br><br>A collection of properties representing different browser features or bugs (Intended for jQuery\'s internal use)',
'length :<br><br>Contains the number of elements in the jQuery object',
'onclick event :<br><br>document.getElementById(\"demo\").onclick = function() {myFunction()};',
'writeln() :<br><br>writes any number of expressions in the document window',
'alert() :<br><br>displays an alert dialog box with a message and an OK button',
'prompt() :<br><br>displays a prompt dialog box with a message and an input field',
'document.writeln(\'&lt;font face=\"Arial\" size=\"5\" color=\"red\"&gt;Hello there!&lt;/font&gt;\'); :<br><br>writes an expression in the document window',
'writeln(), document.write() :<br><br>they are identical, writeln() add with the a newline character',
'window.open(\'link.html\',\'mywindow\'); :<br><br>Opening A Window With JavaScript',
'&lt;a href=\"#\" onClick=\"window.open(\'link.html\',\'mywindow\');\"&gt;Click Here&lt;/a&gt; :<br><br>Opening A Window',
'window.open(\'link.html\',\'mywindow\',\'window features\'); :<br><br>Adding Windows features',
'Link Events :<br><br>onClick, onMouseOver, onMouseOut<br>HTML has the ability to let events trigger actions in a browser<br><br>Window Event<br>Form Events<br>Keyboard Events<br>Mouse Events<br>Drag Events<br>Clipboard Events<br>Media Events<br>Misc Events<br><strong>Link Events</strong>There are nine events that are associated with the links. <table><tbody><tr><td>Event</td><td>Event Handling Attribute</td><td>Description</td></tr><tr><td>Click</td><td>OnClick</td><td>This link event occurred when a user clicks the link.</td></tr><tr><td>DblClick</td><td>OnDblClick</td><td>This link event occurred when a user double clicks the link.</td></tr><tr><td>MouseDown</td><td>OnMouseDown</td><td>This link event occurred when a user presses the mouse button over the link.</td></tr><tr><td>MouseUp</td><td>OnMouseUp</td><td>This link event occurred when a user releases the pressed mouse button.</td></tr><tr><td>MouseOver</td><td>OnMouseOver</td><td>This link event is occurred when the user moves the mouse pointer over a link.</td></tr><tr><td>MouseOut</td><td>OnMouseOut</td><td>This link event is occurred when the user moves he mouse pointer from within a link to outside of that link.</td></tr><tr><td>KeyDown</td><td>OnKeyDown</td><td>This event  is occurred when the user pressed a key on the keyboard.</td></tr><tr><td>KeyUp</td><td>OnKeyUp</td><td>This event handling is occurred when the user release the pressed key of the keyboard.</td></tr><tr><td>KeyPress</td><td>OnKeyPress</td><td>This event handling is occurred when the user presses a key or when the user keeps a key pressed down.</td></tr></tbody></table>',
'&lt;a href=\"index.htm\" onMouseOver=\"home_button.src=\'homeon.gif\';\" onMouseOut=\"home_button.src=\'home.gif\';\"&gt;&lt;img src=\"home.gif\" alt=\"Home\" name=\"home_button\" border=\"0\"&gt;&lt;/a&gt; :<br><br>Assign Link Events',
'if(){}else{} :<br><br>if else function',
'if(){} :<br><br>if function',
'while(){} :<br><br>while function',
'for(){} :<br><br>for function',
'&lt;form name=\"formname\"&gt;&lt;/form&gt; :<br><br>create a form',
'&lt;input type=\"text\" name=\"boxname\"&gt; :<br><br>Place a text box',
'window.document.formname.first_text.value=\'Hi there\'; :<br><br>put \'Hi there!\' into the value of the item called \'first_text\' in the form called \'formname\'',
'onBlur Events :<br><br>when the cursor is moved out of the field',
'onFocus Events :<br><br>when the cursor is moved into the field',
'onChange Events :<br><br>when the field is changed and the cursor moves out of it',
'&lt;input type=\"text\" onBlur=\"dothis\"&gt; :<br><br>onBlur Events',
'function sayhi(){} :<br><br>JavaScript Functions',
'&lt;input type=\"submit\" value=\"Submit\"&gt; :<br><br>Submit Button',
'&lt;form name=\"myform\" onSubmit=\"MyFunction(); return false;\"&gt; :<br><br>onSubmit take action',
'if(window.document.example1.my_checkbox.checked=true){} :<br><br>Checkboxes action',
'switch(expression){case n: ... break; default: ...} :<br><br>Switch Statement',
'switch (new Date().getDay()) {case 5: text = \"Soon it is Weekend\"; break; case 6: text = \"It is Weekend\"; break; default: text = \"Waiting\";} :<br><br>Common week day Code Blocks',
'for (x in person) {text += person[x];} :<br><br>The For/In Loop',
'if (i === 3) { break;}, if (i === 3) { continue;} :<br><br>Break and Continue',
'label: statements; break labelname; continue labelname; :<br><br>JavaScript Labels',
'var array_name = [item1, item2, ...]; :<br><br>Creating an Array',
'arrays use numbered indexes, objects use named indexes :<br><br>Difference Between Arrays and Objects',
'var car = {type:\"Fiat\', model:\"500\', color:\"white\"}; :<br><br>Objects are variables containing many values',
'$(\'.keys\').click(function(){parent.history.back();return false;}); :<br><br>history.back function',
'$(\"#codelist\").load(\"HKCodelist.txt\"); :<br><br>load function',
'set html go to bottom automatically :<br><br>onclick=\"window.scrollTo(0,document.body.scrollHeight);\"',
'javascript load script :<br><br>&lt;script type=\"text/javascript\" src=theUrl&gt;&lt;/script&gt;',
'<h3>HTML DOM Events</h3>abort&emsp;The loading of a media is aborted\nafterprint&emsp;A page has started printing\nanimationend&emsp;A CSS animation has completed\nanimationiteration&emsp;A CSS animation is repeated\nanimationstart&emsp;A CSS animation has started\nbeforeprint&emsp;A page is about to be printed\nbeforeunload&emsp;Before a document is about to be unloaded\nblur&emsp;An element loses focus\ncanplay&emsp;The browser can start playing a media (has buffered enough to begin)\ncanplaythrough&emsp;The browser can play through a media without stopping for buffering\nchange&emsp;The content of a form element has changed\nclick&emsp;An element is clicked on\ncontextmenu&emsp;An element is right-clicked to open a context menu\ncopy&emsp;The content of an element is copied\ncut&emsp;The content of an element is cutted\ndblclick&emsp;An element is double-clicked\ndrag&emsp;An element is being dragged\ndragend&emsp;Dragging of an element has ended\ndragenter&emsp;A dragged element enters the drop target\ndragleave&emsp;A dragged element leaves the drop target\ndragover&emsp;A dragged element is over the drop target\ndragstart&emsp;Dragging of an element has started\ndrop&emsp;A dragged element is dropped on the target\ndurationchange&emsp;The duration of a media is changed\nended&emsp;A media has reach the end ("thanks for listening")\nerror&emsp;An error has occurred while loading a file\nfocus&emsp;An element gets focus\nfocusin&emsp;An element is about to get focus\nfocusout&emsp;An element is about to lose focus\nfullscreenchange&emsp;An element is displayed in fullscreen mode\nfullscreenerror&emsp;An element can not be displayed in fullscreen mode\nhashchange&emsp;There has been changes to the anchor part of a URL\ninput&emsp;An element gets user input\ninvalid&emsp;An element is invalid\nkeydown&emsp;A key is down\nkeypress&emsp;A key is pressed\nkeyup&emsp;A key is released\nload&emsp;An object has loaded\nloadeddata&emsp;Media data is loaded\nloadedmetadata&emsp;Meta data (like dimensions and duration) are loaded\nloadstart&emsp;The browser starts looking for the specified media\nmessage&emsp;A message is received through the event source\nmousedown&emsp;The mouse button is pressed over an element\nmouseenter&emsp;The pointer is moved onto an element\nmouseleave&emsp;The pointer is moved out of an element\nmousemove&emsp;The pointer is moved over an element\nmouseover&emsp;The pointer is moved onto an element\nmouseout&emsp;The pointer is moved out of an element\nmouseup&emsp;A user releases a mouse button over an element\noffline&emsp;The browser starts working offline\nonline&emsp;The browser starts working online\nopen&emsp;A connection with the event source is opened\npagehide&emsp;User navigates away from a webpage\npageshow&emsp;User navigates to a webpage\npaste&emsp;Some content is pasted in an element\npause&emsp;A media is paused\nplay&emsp;The media has started or is no longer paused\nplaying&emsp;The media is playing after beeing paused or buffered\npopstate&emsp;The window\'s history changes\nprogress&emsp;The browser is downloading media data\nratechange&emsp;The playing speed of a media is changed\nresize&emsp;The document view is resized\nreset&emsp;A form is reset\nscroll&emsp;An scrollbar is being scrolled\nsearch&emsp;Something is written in a search field\nseeked&emsp;Skipping to a media position is finished\nseeking&emsp;Skipping to a media position is started\nselect&emsp;User selects some text\nshow&emsp;A <menu> element is shown as a context menu\nstalled&emsp;The browser is trying to get unavailable media data\nstorage&emsp;A Web Storage area is updated\nsubmit&emsp;A form is submitted\nsuspend&emsp;The browser is intentionally not getting media data\ntimeupdate&emsp;The playing position has changed (the user moves to a different point in the media)\ntoggle&emsp;The user opens or closes the <details> element\ntouchcancel&emsp;The touch is interrupted\ntouchend&emsp;A finger is removed from a touch screen\ntouchmove&emsp;A finger is dragged across the screen\ntouchstart&emsp;A finger is placed on a touch screen\ntransitionend&emsp;A CSS transition has completed\nunload&emsp;A page has unloaded\nvolumechange&emsp;The volume of a media is changed (includes muting)\nwaiting&emsp;A media is paused but is expected to resume (e.g. buffering)\nwheel&emsp;The mouse wheel rolls up or down over an element',
'<h3>jQuery Event Methods</h3>\nblur()&emsp;Attaches/Triggers the blur event\nchange()&emsp;Attaches/Triggers the change event\nclick()&emsp;Attaches/Triggers the click event\ndblclick()&emsp;Attaches/Triggers the double click event\nevent.currentTarget&emsp;The current DOM element within the event bubbling phase\nevent.data&emsp;Contains the optional data passed to an event method when the current executing handler is bound\nevent.delegateTarget&emsp;Returns the element where the currently-called jQuery event handler was attached\nevent.isDefaultPrevented()&emsp;Returns whether event.preventDefault() was called for the event object\nevent.isImmediatePropagationStopped()&emsp;Returns whether event.stopImmediatePropagation() was called for the event object\nevent.isPropagationStopped()&emsp;Returns whether event.stopPropagation() was called for the event object\nevent.namespace&emsp;Returns the namespace specified when the event was triggered\nevent.pageX&emsp;Returns the mouse position relative to the left edge of the document\nevent.pageY&emsp;Returns the mouse position relative to the top edge of the document\nevent.preventDefault()&emsp;Prevents the default action of the event\nevent.relatedTarget&emsp;Returns which element being entered or exited on mouse movement\nevent.result&emsp;Contains the last/previous value returned by an event handler triggered by the specified event\nevent.stopImmediatePropagation()&emsp;Prevents other event handlers from being called\nevent.stopPropagation()&emsp;Prevents the event from bubbling up the DOM tree, preventing any parent handlers from being notified of the event\nevent.target&emsp;Returns which DOM element triggered the event\nevent.timeStamp&emsp;Returns the number of milliseconds since January 1, 1970, when the event is triggered\nevent.type&emsp;Returns which event type was triggered\nevent.which&emsp;Returns which keyboard key or mouse button was pressed for the event\nfocus()&emsp;Attaches/Triggers the focus event\nfocusin()&emsp;Attaches an event handler to the focusin event\nfocusout()&emsp;Attaches an event handler to the focusout event\nhover()&emsp;Attaches two event handlers to the hover event\nkeydown()&emsp;Attaches/Triggers the keydown event\nkeypress()&emsp;Attaches/Triggers the keypress event\nkeyup()&emsp;Attaches/Triggers the keyup event\nmousedown()&emsp;Attaches/Triggers the mousedown event\nmouseenter()&emsp;Attaches/Triggers the mouseenter event\nmouseleave()&emsp;Attaches/Triggers the mouseleave event\nmousemove()&emsp;Attaches/Triggers the mousemove event\nmouseout()&emsp;Attaches/Triggers the mouseout event\nmouseover()&emsp;Attaches/Triggers the mouseover event\nmouseup()&emsp;Attaches/Triggers the mouseup event\noff()&emsp;Removes event handlers attached with the on() method\non()&emsp;Attaches event handlers to elements\none()&emsp;Adds one or more event handlers to selected elements. This handler can only be triggered once per element\n$.proxy()&emsp;Takes an existing function and returns a new one with a particular context\nready()&emsp;Specifies a function to execute when the DOM is fully loaded\nresize()&emsp;Attaches/Triggers the resize event\nscroll()&emsp;Attaches/Triggers the scroll event\nselect()&emsp;Attaches/Triggers the select event\nsubmit()&emsp;Attaches/Triggers the submit event\ntrigger()&emsp;Triggers all events bound to the selected elements\ntriggerHandler()&emsp;Triggers all functions bound to a specified event for the selected elements\n',
'$.get() :<br><br>Loads data from a server using an AJAX HTTP GET request<br>Request "test.php" and alert the result of the request:<br>$("button").click(function(){<br>  $.get("test.php", function(data){ alert("Data: " + data); });  <br>});<br>',
'<h4>Global Modules: CommonJS modules Module caching caveats</h4>\nModules are cached based on their resolved filename.\nSince modules may resolve to a different filename based on the location of the calling module (loading from <k>node_modules</k> folders), it is not a <em>guarantee</em> that <k>require(\'foo\')</k> will always return the exact same object, if it would resolve to different files.\nAdditionally, on case-insensitive file systems or operating systems, different resolved filenames can point to the same file, but the cache will still treat them as different modules and will reload the file multiple times.\nFor example,\n<k>require(\'./foo\')</k> and <k>require(\'./FOO\')</k> return two different objects, irrespective of whether or not <k>./foo</k> and <k>./FOO</k> are the same file.',
'<h4>Global Modules: CommonJS modules\n<k>__dirname</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nThe directory name of the current module.\nThis is the same as the <a href="path.html#pathdirnamepath"><k>path.dirname()</k></a> of the <k>__filename</k>.\nExample: running <k>node example.js</k> from <k>/Users/mjr</k>\n<k>console.log(__dirname);\n// Prints: /Users/mjr console.log(path.dirname(__filename));\n// Prints: /Users/mjr</k>',
'<h4>Global Modules: CommonJS modules\n<k>__filename</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nThe file name of the current module.\nThis is the current module file\'s absolute path with symlinks resolved.\nFor a main program this is not necessarily the same as the file name used in the command line.\nSee <k>__dirname</k> for the directory name of the current module.\nExamples:\nRunning <k>node example.js</k> from <k>/Users/mjr</k>\n<k>console.log(__filename);\n// Prints: /Users/mjr/example.js console.log(__dirname);\n// Prints: /Users/mjr</k>\nGiven two modules: <k>a</k> and <k>b</k>, where <k>b</k> is a dependency of\n<k>a</k> and there is a directory structure of:\n<k>/Users/mjr/app/a.js</k>\n<k>/Users/mjr/app/node_modules/b/b.js</k>\nReferences to <k>__filename</k> within <k>b.js</k> will return\n<k>/Users/mjr/app/node_modules/b/b.js</k> while references to <k>__filename</k> within\n<k>a.js</k> will return <k>/Users/mjr/app/a.js</k>.',
'<h4>Global Modules: CommonJS modules\n<k>exports</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object">&lt;Object></a>\nA reference to the <k>module.exports</k> that is shorter to type.\nSee the section about the exports shortcut for details on when to use\n<k>exports</k> and when to use <k>module.exports</k>.',
'<h4>Global Modules: CommonJS modules\n<k>module</k></h4>\n<a href="https://nodejs.org/api/modules.html#the-module-object">&lt;module></a>\nA reference to the current module, see the section about the\n<k>module</k> object.\nIn particular, <k>module.exports</k> is used for defining what a module exports and makes available through <k>require()</k>.',
'<h4>Global Modules: CommonJS modules\n<k>require(id)</k></h4>\n<k>id</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a> module name or path Returns: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types">&lt;any></a> exported module content\nUsed to import modules, <k>JSON</k>, and local files.\nModules can be imported from <k>node_modules</k>.\nLocal modules and JSON files can be imported using a relative path (e.g.\n<k>./</k>, <k>./foo</k>, <k>./bar/baz</k>, <k>../foo</k>) that will be resolved against the directory named by <k>__dirname</k> (if defined) or the current working directory.\nThe relative paths of POSIX style are resolved in an OS independent fashion, meaning that the examples above will work on Windows in the same way they would on Unix systems.\n<k>// Importing a local module with a path relative to the `__dirname` or current\n// working directory.\n(On Windows, this would resolve to .\path\myLocalModule.)\nconst myLocalModule = require(\'./path/myLocalModule\');\n// Importing a JSON file:\nconst jsonData = require(\'./path/filename.json\');\n// Importing a module from node_modules or Node.js built-in module:\nconst crypto = require(\'node:crypto\');</k>',
'<h5>Global Modules: CommonJS modules\n<k>require.cache</k></h5>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object">&lt;Object></a>\nModules are cached in this object when they are required.\nBy deleting a key value from this object, the next <k>require</k> will reload the module.\nThis does not apply to <a href="addons.html">native addons</a>, for which reloading will result in an error.\nAdding or replacing entries is also possible.\nThis cache is checked before built-in modules and if a name matching a built-in module is added to the cache,\nonly <k>node:</k>-prefixed require calls are going to receive the built-in module.\nUse with care!\n<k>const assert = require(\'node:assert\');\nconst realFs = require(\'node:fs\');\nconst fakeFs = {};\nrequire.cache.fs = { exports: fakeFs };\nassert.strictEqual(require(\'fs\'), fakeFs);\nassert.strictEqual(require(\'node:fs\'), realFs);</k>',
'<h5>Global Modules: CommonJS modules\n<k>require.main</k></h5>\n<a href="https://nodejs.org/api/modules.html#the-module-object">&lt;module></a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Undefined_type">&lt;undefined></a>\nThe <k>Module</k> object representing the entry script loaded when the Node.js process launched, or <k>undefined</k> if the entry point of the program is not a CommonJS module.\nSee "Accessing the main module".\nIn <k>entry.js</k> script:\n<k>console.log(require.main);</k>\n<k>node entry.js</k>\n<k>Module {\n  id: \'.\',\n  path: \'/absolute/path/to\',\n  exports: {},\n  filename: \'/absolute/path/to/entry.js\',\n  loaded: false,\n  children: [],\n  paths:\n   [ \'/absolute/path/to/node_modules\',\n     \'/absolute/path/node_modules\',\n     \'/absolute/node_modules\',\n     \'/node_modules\' ] }</k>',
'<h5>Global Modules: CommonJS modules\n<k>require.resolve(request[, options])</k></h5>\n<k>request</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a> The module path to resolve.\n<k>options</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object">&lt;Object></a>\n<k>paths</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string[]></a> Paths to resolve module location from.\nIf present, these paths are used instead of the default resolution paths, with the exception of GLOBAL_FOLDERS like <k>$HOME/.node_modules</k>, which are always included.\nEach of these paths is used as a starting point for the module resolution algorithm, meaning that the <k>node_modules</k> hierarchy is checked from this location.\nReturns: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nUse the internal <k>require()</k> machinery to look up the location of a module,\nbut rather than loading the module, just return the resolved filename.\nIf the module can not be found, a <k>MODULE_NOT_FOUND</k> error is thrown.<h6><k>require.resolve.paths(request)</k>#</h6>\n<k>request</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a> The module path whose lookup paths are being retrieved.\nReturns: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string[]></a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Null_type">&lt;null></a>\nReturns an array containing the paths searched during resolution of <k>request</k> or\n<k>null</k> if the <k>request</k> string references a core module, for example <k>http</k> or\n<k>fs</k>.',
'<h4>Global Modules: CommonJS modules\n<k>module.children</k></h4>\n<a href="https://nodejs.org/api/modules.html#the-module-object">&lt;module[]></a>\nThe module objects required for the first time by this one.',
'<h4>Global Modules: CommonJS modules\n<k>module.exports</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object">&lt;Object></a>\nThe <k>module.exports</k> object is created by the <k>Module</k> system.\nSometimes this is not acceptable; many want their module to be an instance of some class.\nTo do this, assign the desired export object to <k>module.exports</k>.\nAssigning the desired object to <k>exports</k> will simply rebind the local <k>exports</k> variable,\nwhich is probably not what is desired.\nFor example, suppose we were making a module called <k>a.js</k>:\n<k>const EventEmitter = require(\'node:events\');\nmodule.exports = new EventEmitter();\n// Do some work, and after some time emit\n// the \'ready\' event from the module itself.\nsetTimeout(() => {\n  module.exports.emit(\'ready\');\n}, 1000);</k>\nThen in another file we could do:\n<k>const a = require(\'./a\');\na.on(\'ready\', () => {\n  console.log(\'module "a" is ready\');\n});</k>\nAssignment to <k>module.exports</k> must be done immediately.\nIt cannot be done in any callbacks.\nThis does not work:\n<k>x.js</k>:\n<k>setTimeout(() => {\n  module.exports = { a: \'hello\' };\n}, 0);</k>\n<k>y.js</k>:\n<k>const x = require(\'./x\');\nconsole.log(x.a);</k>',
'<h5>Global Modules: CommonJS modules\n<k>exports</k> shortcut</h5>\nThe <k>exports</k> variable is available within a module\'s file-level scope, and is assigned the value of <k>module.exports</k> before the module is evaluated.\nIt allows a shortcut, so that <k>module.exports.f = ...</k> can be written more succinctly as <k>exports.f = ...</k>.\nHowever, be aware that like any variable, if a new value is assigned to <k>exports</k>, it is no longer bound to <k>module.exports</k>:\n<k>module.exports.hello = true; // Exported from require of module exports = { hello: false };  // Not exported, only available in the module</k>\nWhen the <k>module.exports</k> property is being completely replaced by a new object, it is common to also reassign <k>exports</k>:\n<k>module.exports = exports = function Constructor() {\n  // ...\netc.\n};</k>\nTo illustrate the behavior, imagine this hypothetical implementation of\n<k>require()</k>, which is quite similar to what is actually done by <k>require()</k>:\n<k>function require(/* ...\n*/) {\n  const module = { exports: {} };\n  ((module, exports) => {\n    // Module code here.\nIn this example, define a function.\n    function someFunc() {}\n    exports = someFunc;\n    // At this point, exports is no longer a shortcut to module.exports, and\n    // this module will still export an empty default object.\n    module.exports = someFunc;\n    // At this point, the module will now export someFunc, instead of the\n    // default object.\n  })(module, module.exports);\n  return module.exports;\n}</k>',
'<h4>Global Modules: CommonJS modules\n<k>module.filename</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nThe fully resolved filename of the module.',
'<h4>Global Modules: CommonJS modules\n<k>module.id</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nThe identifier for the module.\nTypically this is the fully resolved filename.',
'<h4>Global Modules: CommonJS modules\n<k>module.isPreloading</k></h4>\nType: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type">&lt;boolean></a> <k>true</k> if the module is running during the Node.js preload phase.',
'<h4>Global Modules: CommonJS modules\n<k>module.loaded</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type">&lt;boolean></a>\nWhether or not the module is done loading, or is in the process of loading.',
'<h4>Global Modules: CommonJS modules\n<k>module.parent</k></h4>\nDeprecated: Please use <k>require.main</k> and\n<k>module.children</k> instead.\n<a href="https://nodejs.org/api/modules.html#the-module-object">&lt;module></a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Null_type">&lt;null></a> | <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Undefined_type">&lt;undefined></a>\nThe module that first required this one, or <k>null</k> if the current module is the entry point of the current process, or <k>undefined</k> if the module was loaded by something that is not a CommonJS module (E.G.: REPL or <k>import</k>).',
'<h4>Global Modules: CommonJS modules\n<k>module.path</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nThe directory name of the module.\nThis is usually the same as the\n<a href="path.html#pathdirnamepath"><k>path.dirname()</k></a> of the <k>module.id</k>.',
'<h4>Global Modules: CommonJS modules\n<k>module.paths</k></h4>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string[]></a>\nThe search paths for the module.',
'<h4>Global Modules: CommonJS modules\n<k>module.require(id)</k></h4>\n<k>id</k> <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#String_type">&lt;string></a>\nReturns: <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Data_types">&lt;any></a> exported module content\nThe <k>module.require()</k> method provides a way to load a module as if\n<k>require()</k> was called from the original module.\nIn order to do this, it is necessary to get a reference to the <k>module</k> object.\nSince <k>require()</k> returns the <k>module.exports</k>, and the <k>module</k> is typically\n<em>only</em> available within a specific module\'s code, it must be explicitly exported in order to be used.',
'<h3>Global Modules: CommonJS modules</h3>\nCommonJS modules are the original way to package JavaScript code for Node.js.\nNode.js also supports the <a href="esm.html">ECMAScript modules</a> standard used by browsers and other JavaScript runtimes.\nIn Node.js, each file is treated as a separate module.\nFor example, consider a file named <k>foo.js</k>:\n<k>const circle = require(\'./circle.js\');\nconsole.log(`The area of a circle of radius 4 is ${circle.area(4)}`);</k>\nOn the first line, <k>foo.js</k> loads the module <k>circle.js</k> that is in the same directory as <k>foo.js</k>.\nHere are the contents of <k>circle.js</k>:\n<k>const { PI } = Math;\nexports.area = (r) => PI * r ** 2;\nexports.circumference = (r) => 2 * PI * r;</k>\nThe module <k>circle.js</k> has exported the functions <k>area()</k> and\n<k>circumference()</k>.\nFunctions and objects are added to the root of a module by specifying additional properties on the special <k>exports</k> object.\nVariables local to the module will be private, because the module is wrapped in a function by Node.js (see module wrapper).\nIn this example, the variable <k>PI</k> is private to <k>circle.js</k>.\nThe <k>module.exports</k> property can be assigned a new value (such as a function or object).\nBelow, <k>bar.js</k> makes use of the <k>square</k> module, which exports a Square class:\n<k>const Square = require(\'./square.js\');\nconst mySquare = new Square(2);\nconsole.log(`The area of mySquare is ${mySquare.area()}`);</k>\nThe <k>square</k> module is defined in <k>square.js</k>:\n<k>// Assigning to exports will not modify module, must use module.exports module.exports = class Square {\n  constructor(width) {\n    this.width = width;\n  }\n  area() {\n    return this.width ** 2;\n  }\n};</k>\nThe CommonJS module system is implemented in the <a href="https://nodejs.org/api/module.html"><k>module</k> core module</a>.',
'<h3>Global Modules: CommonJS modules Enabling</h3>\nNode.js has two module systems: CommonJS modules and <a href="esm.html">ECMAScript modules</a>.\nBy default, Node.js will treat the following as CommonJS modules:\nFiles with a <k>.cjs</k> extension;\nFiles with a <k>.js</k> extension when the nearest parent <k>package.json</k> file contains a top-level field <a href="packages.html#type"><k>"type"</k></a> with a value of <k>"commonjs"</k>.\nFiles with a <k>.js</k> extension when the nearest parent <k>package.json</k> file doesn\'t contain a top-level field <a href="packages.html#type"><k>"type"</k></a>.\nPackage authors should include the <a href="packages.html#type"><k>"type"</k></a> field, even in packages where all sources are CommonJS.\nBeing explicit about the <k>type</k> of the package will make things easier for build tools and loaders to determine how the files in the package should be interpreted.\nFiles with an extension that is not <k>.mjs</k>, <k>.cjs</k>, <k>.json</k>, <k>.node</k>, or <k>.js</k>\n(when the nearest parent <k>package.json</k> file contains a top-level field\n<a href="packages.html#type"><k>"type"</k></a> with a value of <k>"module"</k>, those files will be recognized as CommonJS modules only if they are being included via <k>require()</k>, not when used as the command-line entry point of the program).\nSee <a href="packages.html#determining-module-system">Determining module system</a> for more details.\nCalling <k>require()</k> always use the CommonJS module loader.\nCalling <k>import()</k>\nalways use the ECMAScript module loader.',
'<h3>Global Modules: CommonJS modules Accessing the main module</h3>\nWhen a file is run directly from Node.js, <k>require.main</k> is set to its\n<k>module</k>.\nThat means that it is possible to determine whether a file has been run directly by testing <k>require.main === module</k>.\nFor a file <k>foo.js</k>, this will be <k>true</k> if run via <k>node foo.js</k>, but\n<k>false</k> if run by <k>require(\'./foo\')</k>.\nWhen the entry point is not a CommonJS module, <k>require.main</k> is <k>undefined</k>, and the main module is out of reach.',
'<h3>Global Modules: CommonJS modules Package manager tips</h3>\nThe semantics of the Node.js <k>require()</k> function were designed to be general enough to support reasonable directory structures.\nPackage manager programs such as <k>dpkg</k>, <k>rpm</k>, and <k>npm</k> will hopefully find it possible to build native packages from Node.js modules without modification.\nBelow we give a suggested directory structure that could work:\nLet\'s say that we wanted to have the folder at\n<k>/usr/lib/node/&lt;some-package>/&lt;some-version></k> hold the contents of a specific version of a package.\nPackages can depend on one another.\nIn order to install package <k>foo</k>, it may be necessary to install a specific version of package <k>bar</k>.\nThe <k>bar</k> package may itself have dependencies, and in some cases, these may even collide or form cyclic dependencies.\nBecause Node.js looks up the <k>realpath</k> of any modules it loads (that is, it resolves symlinks) and then looks for their dependencies in <k>node_modules</k> folders, this situation can be resolved with the following architecture:\n<k>/usr/lib/node/foo/1.2.3/</k>: Contents of the <k>foo</k> package, version 1.2.3.\n<k>/usr/lib/node/bar/4.3.2/</k>: Contents of the <k>bar</k> package that <k>foo</k> depends on.\n<k>/usr/lib/node/foo/1.2.3/node_modules/bar</k>: Symbolic link to\n<k>/usr/lib/node/bar/4.3.2/</k>.\n<k>/usr/lib/node/bar/4.3.2/node_modules/*</k>: Symbolic links to the packages that\n<k>bar</k> depends on.\nThus, even if a cycle is encountered, or if there are dependency conflicts, every module will be able to get a version of its dependency that it can use.\nWhen the code in the <k>foo</k> package does <k>require(\'bar\')</k>, it will get the version that is symlinked into <k>/usr/lib/node/foo/1.2.3/node_modules/bar</k>.\nThen, when the code in the <k>bar</k> package calls <k>require(\'quux\')</k>, it\'ll get the version that is symlinked into\n<k>/usr/lib/node/bar/4.3.2/node_modules/quux</k>.\nFurthermore, to make the module lookup process even more optimal, rather than putting packages directly in <k>/usr/lib/node</k>, we could put them in\n<k>/usr/lib/node_modules/&lt;name>/&lt;version></k>.\nThen Node.js will not bother looking for missing dependencies in <k>/usr/node_modules</k> or <k>/node_modules</k>.\nIn order to make modules available to the Node.js REPL, it might be useful to also add the <k>/usr/lib/node_modules</k> folder to the <k>$NODE_PATH</k> environment variable.\nSince the module lookups using <k>node_modules</k> folders are all relative, and based on the real path of the files making the calls to\n<k>require()</k>, the packages themselves can be anywhere.',
'<h3>Global Modules: CommonJS modules The <k>.mjs</k> extension</h3>\nDue to the synchronous nature of <k>require()</k>, it is not possible to use it to load ECMAScript module files.\nAttempting to do so will throw a\n<a href="errors.html#err_require_esm"><k>ERR_REQUIRE_ESM</k></a> error.\nUse <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import"><k>import()</k></a> instead.\nThe <k>.mjs</k> extension is reserved for <a href="esm.html">ECMAScript Modules</a> which cannot be loaded via <k>require()</k>.\nSee <a href="packages.html#determining-module-system">Determining module system</a> section for more info regarding which files are parsed as ECMAScript modules.',
'<h3>Global Modules: CommonJS modules All together</h3>\nTo get the exact filename that will be loaded when <k>require()</k> is called, use the <k>require.resolve()</k> function.\nPutting together all of the above, here is the high-level algorithm in pseudocode of what <k>require()</k> does:\nrequire(X) from module at path Y\n1. If X is a core module,\n   a. return the core module\n   b. STOP\n2. If X begins with \'/\'\n   a. set Y to be the filesystem root\n3. If X begins with \'./\' or \'/\' or \'../\'\n   a. LOAD_AS_FILE(Y + X)\n   b. LOAD_AS_DIRECTORY(Y + X)\n   c. THROW "not found"\n4. If X begins with \'#\'\n   a. LOAD_PACKAGE_IMPORTS(X, dirname(Y))\n5. LOAD_PACKAGE_SELF(X, dirname(Y))\n6. LOAD_NODE_MODULES(X, dirname(Y))\n7. THROW "not found"\nLOAD_AS_FILE(X)\n1. If X is a file, load X as its file extension format.\nSTOP\n2. If X.js is a file, load X.js as JavaScript text.\nSTOP\n3. If X.json is a file, parse X.json to a JavaScript Object.\nSTOP\n4. If X.node is a file, load X.node as binary addon.\nSTOP\nLOAD_INDEX(X)\n1. If X/index.js is a file, load X/index.js as JavaScript text.\nSTOP\n2. If X/index.json is a file, parse X/index.json to a JavaScript object.\nSTOP\n3. If X/index.node is a file, load X/index.node as binary addon.\nSTOP\nLOAD_AS_DIRECTORY(X)\n1. If X/package.json is a file,\n   a. Parse X/package.json, and look for "main" field.\n   b. If "main" is a falsy value, GOTO 2.\n   c. let M = X + (json main field)\n   d. LOAD_AS_FILE(M)\n   e. LOAD_INDEX(M)\n   f. LOAD_INDEX(X) DEPRECATED\n   g. THROW "not found"\n2. LOAD_INDEX(X)\nLOAD_NODE_MODULES(X, START)\n1. let DIRS = NODE_MODULES_PATHS(START)\n2. for each DIR in DIRS:\n   a.LOAD_PACKAGE_EXPORTS(X, DIR)\n   b.LOAD_AS_FILE(DIR/X)\n   c.LOAD_AS_DIRECTORY(DIR/X)\nNODE_MODULES_PATHS(START)\n1. let PARTS = path split(START)\n2. let I = count of PARTS - 1\n3. let DIRS = []\n4. while I >= 0,\n   a.if PARTS[I] = "node_modules" CONTINUE\n   b.DIR = path join(PARTS[0 ..\nI] + "node_modules")\n   c.DIRS = DIR + DIRS\n   d.let I = I - 1\n5. return DIRS + GLOBAL_FOLDERS\nLOAD_PACKAGE_IMPORTS(X, DIR)\n1. Find the closest package scope SCOPE to DIR.\n2. If no scope was found, return.\n3. If the SCOPE/package.json "imports" is null or undefined, return.\n4. let MATCH = PACKAGE_IMPORTS_RESOLVE(X, pathToFileURL(SCOPE),\n  ["node", "require"]) <a href="esm.md#resolver-algorithm-specification">defined in the ESM resolver</a>.\n5. RESOLVE_ESM_MATCH(MATCH).\nLOAD_PACKAGE_EXPORTS(X, DIR)\n1. Try to interpret X as a combination of NAME and SUBPATH where the name may have a @scope/ prefix and the subpath begins with a slash (`/`).\n2. If X does not match this pattern or DIR/NAME/package.json is not a file, return.\n3. Parse DIR/NAME/package.json, and look for "exports" field.\n4. If "exports" is null or undefined, return.\n5. let MATCH = PACKAGE_EXPORTS_RESOLVE(pathToFileURL(DIR/NAME), "." + SUBPATH, `package.json` "exports", ["node", "require"]) <a href="esm.md#resolver-algorithm-specification">defined in the ESM resolver</a>.\n6. RESOLVE_ESM_MATCH(MATCH)\nLOAD_PACKAGE_SELF(X, DIR)\n1. Find the closest package scope SCOPE to DIR.\n2. If no scope was found, return.\n3. If the SCOPE/package.json "exports" is null or undefined, return.\n4. If the SCOPE/package.json "name" is not the first segment of X, return.\n5. let MATCH = PACKAGE_EXPORTS_RESOLVE(pathToFileURL(SCOPE), "." + X.slice("name".length), `package.json` "exports", ["node", "require"]) <a href="esm.md#resolver-algorithm-specification">defined in the ESM resolver</a>.\n6. RESOLVE_ESM_MATCH(MATCH)\nRESOLVE_ESM_MATCH(MATCH)\n1. let RESOLVED_PATH = fileURLToPath(MATCH)\n2. If the file at RESOLVED_PATH exists, load RESOLVED_PATH as its extension format.\nSTOP\n3. THROW "not found"',
'<h3>Global Modules: CommonJS modules Caching</h3>\nModules are cached after the first time they are loaded.\nThis means (among other things) that every call to <k>require(\'foo\')</k> will get exactly the same object returned, if it would resolve to the same file.\nProvided <k>require.cache</k> is not modified, multiple calls to <k>require(\'foo\')</k> will not cause the module code to be executed multiple times.\nThis is an important feature.\nWith it, "partially done" objects can be returned, thus allowing transitive dependencies to be loaded even when they would cause cycles.\nTo have a module execute code multiple times, export a function, and call that function.',
'<h3>Global Modules: CommonJS modules Core modules</h3>\nNode.js has several modules compiled into the binary.\nThese modules are described in greater detail elsewhere in this documentation.\nThe core modules are defined within the Node.js source and are located in the\n<k>lib/</k> folder.\nCore modules can be identified using the <k>node:</k> prefix, in which case it bypasses the <k>require</k> cache.\nFor instance, <k>require(\'node:http\')</k> will always return the built in HTTP module, even if there is <k>require.cache</k> entry by that name.\nSome core modules are always preferentially loaded if their identifier is passed to <k>require()</k>.\nFor instance, <k>require(\'http\')</k> will always return the built-in HTTP module, even if there is a file by that name.\nThe list of core modules that can be loaded without using the <k>node:</k> prefix is exposed as <a href="https://nodejs.org/api/module.html#modulebuiltinmodules"><k>module.builtinModules</k></a>.',
'<h3>Global Modules: CommonJS modules Cycles</h3>\nWhen there are circular <k>require()</k> calls, a module might not have finished executing when it is returned.\nConsider this situation:\n<k>a.js</k>:\n<k>console.log(\'a starting\');\nexports.done = false;\nconst b = require(\'./b.js\');\nconsole.log(\'in a, b.done = %j\', b.done);\nexports.done = true;\nconsole.log(\'a done\');</k>\n<k>b.js</k>:\n<k>console.log(\'b starting\');\nexports.done = false;\nconst a = require(\'./a.js\');\nconsole.log(\'in b, a.done = %j\', a.done);\nexports.done = true;\nconsole.log(\'b done\');</k>\n<k>main.js</k>:\n<k>console.log(\'main starting\');\nconst a = require(\'./a.js\');\nconst b = require(\'./b.js\');\nconsole.log(\'in main, a.done = %j, b.done = %j\', a.done, b.done);</k>\nWhen <k>main.js</k> loads <k>a.js</k>, then <k>a.js</k> in turn loads <k>b.js</k>.\nAt that point, <k>b.js</k> tries to load <k>a.js</k>.\nIn order to prevent an infinite loop, an <strong>unfinished copy</strong> of the <k>a.js</k> exports object is returned to the\n<k>b.js</k> module.\n<k>b.js</k> then finishes loading, and its <k>exports</k> object is provided to the <k>a.js</k> module.\nBy the time <k>main.js</k> has loaded both modules, they\'re both finished.\nThe output of this program would thus be:\n<k>$ node main.js main starting a starting b starting in b, a.done = false b done in a, b.done = true a done in main, a.done = true, b.done = true</k>\nCareful planning is required to allow cyclic module dependencies to work correctly within an application.',
'<h3>Global Modules: CommonJS modules File modules</h3>\nIf the exact filename is not found, then Node.js will attempt to load the required filename with the added extensions: <k>.js</k>, <k>.json</k>, and finally\n<k>.node</k>.\nWhen loading a file that has a different extension (e.g.\n<k>.cjs</k>), its full name must be passed to <k>require()</k>, including its file extension (e.g.\n<k>require(\'./file.cjs\')</k>).\n<k>.json</k> files are parsed as JSON text files, <k>.node</k> files are interpreted as compiled addon modules loaded with <k>process.dlopen()</k>.\nFiles using any other extension (or no extension at all) are parsed as JavaScript text files.\nRefer to the <a href="packages.html#determining-module-system">Determining module system</a> section to understand what parse goal will be used.\nA required module prefixed with <k>\'/\'</k> is an absolute path to the file.\nFor example, <k>require(\'/home/marco/foo.js\')</k> will load the file at\n<k>/home/marco/foo.js</k>.\nA required module prefixed with <k>\'./\'</k> is relative to the file calling\n<k>require()</k>.\nThat is, <k>circle.js</k> must be in the same directory as <k>foo.js</k> for\n<k>require(\'./circle\')</k> to find it.\nWithout a leading <k>\'/\'</k>, <k>\'./\'</k>, or <k>\'../\'</k> to indicate a file, the module must either be a core module or is loaded from a <k>node_modules</k> folder.\nIf the given path does not exist, <k>require()</k> will throw a\n<a href="errors.html#module_not_found"><k>MODULE_NOT_FOUND</k></a> error.',
'<h3>Global Modules: CommonJS modules Folders as modules</h3>\nThere are three ways in which a folder may be passed to <k>require()</k> as an argument.\nThe first is to create a <a href="packages.html#nodejs-packagejson-field-definitions"><k>package.json</k></a> file in the root of the folder,\nwhich specifies a <k>main</k> module.\nAn example <a href="packages.html#nodejs-packagejson-field-definitions"><k>package.json</k></a> file might look like this:\n<k>{ "name" : "some-library",\n  "main" : "./lib/some-library.js" }</k>\nIf this was in a folder at <k>./some-library</k>, then\n<k>require(\'./some-library\')</k> would attempt to load\n<k>./some-library/lib/some-library.js</k>.\nIf there is no <a href="packages.html#nodejs-packagejson-field-definitions"><k>package.json</k></a> file present in the directory, or if the\n<a href="packages.html#main"><k>"main"</k></a> entry is missing or cannot be resolved, then Node.js will attempt to load an <k>index.js</k> or <k>index.node</k> file out of that directory.\nFor example, if there was no <a href="packages.html#nodejs-packagejson-field-definitions"><k>package.json</k></a> file in the previous example, then <k>require(\'./some-library\')</k> would attempt to load:\n<k>./some-library/index.js</k>\n<k>./some-library/index.node</k>\nIf these attempts fail, then Node.js will report the entire module as missing with the default error:\n<k>Error: Cannot find module \'some-library\'</k>\nIn all three above cases, an <k>import(\'./some-library\')</k> call would result in a\n<a href="errors.html#err_unsupported_dir_import"><k>ERR_UNSUPPORTED_DIR_IMPORT</k></a> error.\nUsing package <a href="packages.html#subpath-exports">subpath exports</a> or\n<a href="packages.html#subpath-imports">subpath imports</a> can provide the same containment organization benefits as folders as modules, and work for both <k>require</k> and <k>import</k>.',
'<h3>Global Modules: CommonJS modules Loading from <k>node_modules</k> folders</h3>\nIf the module identifier passed to <k>require()</k> is not a core module, and does not begin with <k>\'/\'</k>, <k>\'../\'</k>, or\n<k>\'./\'</k>, then Node.js starts at the directory of the current module, and adds <k>/node_modules</k>, and attempts to load the module from that location.\nNode.js will not append <k>node_modules</k> to a path already ending in\n<k>node_modules</k>.\nIf it is not found there, then it moves to the parent directory, and so on, until the root of the file system is reached.\nFor example, if the file at <k>\'/home/ry/projects/foo.js\'</k> called\n<k>require(\'bar.js\')</k>, then Node.js would look in the following locations, in this order:\n<k>/home/ry/projects/node_modules/bar.js</k>\n<k>/home/ry/node_modules/bar.js</k>\n<k>/home/node_modules/bar.js</k>\n<k>/node_modules/bar.js</k>\nThis allows programs to localize their dependencies, so that they do not clash.\nIt is possible to require specific files or sub modules distributed with a module by including a path suffix after the module name.\nFor instance\n<k>require(\'example-module/path/to/file\')</k> would resolve <k>path/to/file</k>\nrelative to where <k>example-module</k> is located.\nThe suffixed path follows the same module resolution semantics.',
'<h3>Global Modules: CommonJS modules Loading from the global folders</h3>\nIf the <k>NODE_PATH</k> environment variable is set to a colon-delimited list of absolute paths, then Node.js will search those paths for modules if they are not found elsewhere.\nOn Windows, <k>NODE_PATH</k> is delimited by semicolons (<k>;</k>) instead of colons.\n<k>NODE_PATH</k> was originally created to support loading modules from varying paths before the current module resolution algorithm was defined.\n<k>NODE_PATH</k> is still supported, but is less necessary now that the Node.js ecosystem has settled on a convention for locating dependent modules.\nSometimes deployments that rely on <k>NODE_PATH</k> show surprising behavior when people are unaware that <k>NODE_PATH</k> must be set.\nSometimes a module\'s dependencies change, causing a different version (or even a different module) to be loaded as the <k>NODE_PATH</k> is searched.\nAdditionally, Node.js will search in the following list of GLOBAL_FOLDERS:\n1: <k>$HOME/.node_modules</k>\n2: <k>$HOME/.node_libraries</k>\n3: <k>$PREFIX/lib/node</k>\nWhere <k>$HOME</k> is the user\'s home directory, and <k>$PREFIX</k> is the Node.js configured <k>node_prefix</k>.\nThese are mostly for historic reasons.\nIt is strongly encouraged to place dependencies in the local <k>node_modules</k>\nfolder.\nThese will be loaded faster, and more reliably.',
'<h3>Global Modules: CommonJS modules The module wrapper</h3>\nBefore a module\'s code is executed, Node.js will wrap it with a function wrapper that looks like the following:\n<k>(function(exports, require, module, __filename, __dirname) {\n// Module code actually lives in here\n});</k>\nBy doing this, Node.js achieves a few things:\nIt keeps top-level variables (defined with <k>var</k>, <k>const</k>, or <k>let</k>) scoped to the module rather than the global object.\nIt helps to provide some global-looking variables that are actually specific to the module, such as:\nThe <k>module</k> and <k>exports</k> objects that the implementor can use to export values from the module.\nThe convenience variables <k>__filename</k> and <k>__dirname</k>, containing the module\'s absolute filename and directory path.\n',
'<h3>Global Modules: CommonJS modules The <k>module</k> object</h3>\n<a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object">&lt;Object></a>\nIn each module, the <k>module</k> free variable is a reference to the object representing the current module.\nFor convenience, <k>module.exports</k> is also accessible via the <k>exports</k> module-global.\n<k>module</k> is not actually a global but rather local to each module.',
'<h3>Global Modules: CommonJS modules The <k>Module</k> object</h3>\nThis section was moved to\n<a href="https://nodejs.org/api/module.html#the-module-object">Modules: <k>module</k> core module</a>.\n<a href="https://nodejs.org/api/module.html#modulebuiltinmodules"><k>module.builtinModules</k></a>\n<a href="https://nodejs.org/api/module.html#modulecreaterequirefilename"><k>module.createRequire(filename)</k></a>\n<a href="https://nodejs.org/api/module.html#modulesyncbuiltinesmexports"><k>module.syncBuiltinESMExports()</k></a>',
'<h3>Global Modules: CommonJS modules Source map v3 support</h3>\nThis section was moved to\n<a href="https://nodejs.org/api/module.html#source-map-v3-support">Modules: <k>module</k> core module</a>.\n<a href="https://nodejs.org/api/module.html#modulefindsourcemappath"><k>module.findSourceMap(path)</k></a>\n<a href="https://nodejs.org/api/module.html#class-modulesourcemap">Class: <k>module.SourceMap</k></a>\n<a href="https://nodejs.org/api/module.html#new-sourcemappayload"><k>new SourceMap(payload)</k></a>\n<a href="https://nodejs.org/api/module.html#sourcemappayload"><k>sourceMap.payload</k></a>\n<a href="https://nodejs.org/api/module.html#sourcemapfindentrylinenumber-columnnumber"><k>sourceMap.findEntry(lineNumber, columnNumber)</k></a>',
'<h3>JavaScript Promises</h3>\n"Producing code" is code that can take some time\n"Consuming code" is code that must wait for the result\nA Promise is a JavaScript object that links producing code and consuming code\nA JavaScript Promise object contains both the producing code and calls to the consuming code:\nlet myPromise = new Promise(function(myResolve, myReject) {\n// "Producing Code" (May take some time)\n  myResolve(); // when successful\n  myReject();  // when error\n});\n// "Consuming Code" (Must wait for a fulfilled Promise)\nmyPromise.then(\n  function(value) { /* code if successful */ },\n  function(error) { /* code if some error */ }\n);\nhow to use a Promise:\nmyPromise.then(\n  function(value) { /* code if successful */ },\n  function(error) { /* code if some error */ }\n);\nPromise.then() takes two arguments, a callback for success and another for failure.\nBoth are optional, so you can add a callback for success or failure only.\n\nExample\nfunction getFile(myCallback) {\n  let req = new XMLHttpRequest();\n  req.open(\'GET\', "mycar.html");\n  req.onload = function() {\n    if (req.status == 200) {\n      myCallback(req.responseText);\n    } else {\n      myCallback("Error: " + req.status);\n    }\n  }\n  req.send();\n}\ngetFile(myDisplayer);\n',

];
bookid = "C Tips"
initSelectRange = 50
