const quizData = [
"What is the capital of France?\tParis",
"What is 2 + 2?\t4",
"What color is the sky?\tBlue",
"What is the largest planet?\tJupiter",
"Who wrote Hamlet?\tShakespeare",
"What is H2O?\tWater",
"How many continents are there?\t7",
"What is the square root of 64?\t8",
"What year did WWII end?\t1945",
"What is the fastest land animal?\tCheetah",
"What is the chemical symbol for gold?\tAu",
"How many sides does a triangle have?\t3",
"What is the freezing point of water?\t0",
"Who painted the Mona Lisa?\tDa Vinci",
"What is the largest ocean?\tPacific",
"antique, antiquated and wrong, defends antiquated laws, antiquarian, antiquarian bookseller	陳舊的 过时的, 过时的和错误的, 捍卫过时的法律, 古文物研究者 收集古文物者 古文物研究的, 古籍书店 obsolete, archaic, belated, unhip, corny",
"AOB	Any Other Business 其他事项",
"arcane, arcana, arcana of the debate	神秘 隐藏的, 奥秘 秘密 秘方 艰深的知识, 辩论的秘密 奥秘 secret, hidden cryptic, mysterious, latent, secret formula, secret recipe, secrets or mysteries",
"basalt	玄武岩",
"commit, commit a terrorist attack, be committed to, committed by fools, more committed to Jesus, not committed to achieving, committed to enhancing quality of life, pot committed, pot-committed	保证 承诺 发送 提交 犯罪 监禁 全心投入 决心从事…, 发动恐怖袭击, 对…作出承诺 致力于 坚持, 傻瓜的承诺, 更致力于耶稣, 不致力于实现, 致力于提高生活质量, 被套牢 骑虎难下 dedication, delegation, consignment, agree, hand over, imprison, promise, consent, accept, undertake to do",
"be faced with, face exclusion, face reality, face jailing, must be faced head-on, in the face of adversity, faced setbacks in the past, faces an ever-shifting end point, in the face of public grumblings	面对某种局面, 面对排斥, 面对现实, 面对监狱, 必须面对正面, 面对逆境, 过去面对挫折, 面临着不断变化的终点, 在公众抱怨的情况下",
"Cavern	洞穴",
"chock, chock full, bearing chock, chock against the wall, chocked up with newspapers	牢牢地 紧紧地 满满地 塞满 楔子, 塞满了的, 轴承座, 靠墙塞住, 塞满了报纸 to cram full",
"coffer, Cofferdam, coffers are deprived of, the state coffers, coffers of the government	保险箱 金库 资金 围堰, 围堰, 金库被剥夺了, 国库, 政府金库 cofferdam, chest, crate, trunk, package",
"conspire, conspired to smear, conspiratorial tendencies, common traps with this conspiracy, on six counts of fraud and conspiracy, conspiracy, to concoct conspiracy, Conspiracy Theorists	图谋, 密谋抹黑, 阴谋倾向, 这个阴谋的共同陷阱, 六项欺诈和阴谋罪, 阴谋, 捏造一个阴谋, 阴谋论者 plot, scheme, machination, complicity, collusion",
"contend, to contend with, legitimate contender, transformed into a legitimate contender, contending with an extremely low ceiling, contend with devastating natural disasters	斗争 抗衡, 抗衡 竞争 角逐, 合法的竞争者, 变成了合法的竞争者, 与极低的天花板搏斗, 与毁灭性的自然灾害抗争 struggle, fight, dispute, strive, vie, rival, compete, emulate, battle",
"deficit, deficient, budget deficit, runaway deficits, trade deficit, fiscal deficit, current account deficit	逆差、亏损、赤字, 不足的 有限的 微薄的 scant, sparing, 预算赤字 财政赤字 赤字预算, 失控的赤字, 贸易逆差 贸易赤字, 财政赤字, 经常账目赤字",
"diversify into	进入某个领域 朝某个方向发展",
"emancipate, emancipation, emancipated slaves, emancipation of individuals	使自由 不受束缚 解脱 解放, 自立 解放 释放 解脱, 解放奴隶, 解放的个人 release, free, unloose, loose, liberate, manumit",
"emerge, emerged as, it emerged that, emerge intact and victorious, Information emerges only through leaks	浮现 出现 形成, 成为, 后来得知 事实表明 结果发现 有消息称, 完好无缺地胜利出现, 信息只能通过泄漏产生",
"esoteric	深奥的",
"exasperating, exasperated sigh, every exasperated partner	激怒 使人恼怒的, 十分恼怒地叹气, 每一个愤怒的伙伴 aggravated, annoy, irritate, provoke, tick off, infuriated, cheesed off, browned off",
"fuss, fuss about a few mosquitoes, fussy, what the fuss is all about	大惊小怪 小题大作, 对几只蚊子大惊小怪的, 大惊小怪的 過分挑剔的 難以滿足的 过分琐碎的, 是什么大惊小怪 agitation, bustle, disturbance, flurry, tempest in a teapot",
"happy with sb./sth	对某人某事表示满意",
"tout, widely touted legend, a habit of touting overambitious launch schedules, touted the latest harsh sanctions, have long touted	吹嘘 自夸 兜售 吹捧 招徕, 被广泛吹捧的传奇, 吹嘘雄心勃勃的发射计划的习惯, 吹捧最新的严厉制裁, 长期吹捧 drum up, hawk, seek a vote, vaunt, boasted about, brag about, bravado, crow about, puff up",
"infrastructure	基础设施（如运输、通讯、银行制度等） 基础结构",
"insecticides	杀虫剂",
"In my view, KIV, in the rearview mirror, reviewing stands, first print interview, preview our activities, highest viewership rating, a view shared by many of her supporters, in view of	在我看来 我认为, Keep In View 放在心里, 在后视镜中, 检阅台 观礼台 阅兵台, 第一次印刷采访, 预览我们的活动, 最高收视率, 许多她的支持者都认同这一观点, 鉴于 in consideration of seeing that",
"Lay-By	路側停車處",
"nefarious, fulfil nefarious designs	邪恶, 实现邪恶的设计 daemoniacal, dangerous, demonic, evil, heretical, perilous, sinister, vicious",
"proposes countermeasures and suggestions, The proposed new structure is notable for its shape	提出了对策和建議, 拟建的新建筑因其外形令人瞩目",
"plinth	底座 基座 柱基 foundation, base",
"professes, associate professor, continue to profess	宣称信奉 正式准予加入 声称 承认 当教授, 副教授, 继续信奉",
"recession, recessionary, recession-proof, global recession is on the way, stress-tested by recession, tip them over into recession, shecession	衰退期 经济衰退的 引起经济衰退的, 抗衰退, 全球经济衰退即将来临, 受经济衰退压力测试, 使他们陷入衰退 倾覆, 主要对女性造成影响的经济衰退",
"instate, reinstate, re-instate, reinstatement Works, reinstate the expelled legislators, reinstated following a recount	安置 建立 任命, 恢复 复原 還原, 修復工程, 恢复被驱逐议员的职务, 重新计票后恢复 restore, recover, resume, regain, rehabilitate",
"remains, remained coy, remain silent, remains unclear, burnt out remains, remain bulletproof, remains to be seen, They remain behind, remain in the closet, still remains a challenge	遗骨 残骸 遗迹 废墟 遗址 剩余 保持 依然 继续 留下, 保持假装害羞无知的 含糊其辞的, 保持沉默, 还不清楚, 被烧毁的遗迹, 保持防弹, 有待观察, 他们仍然留在原地, 呆在壁橱里, 仍然是一个挑战",
"salvage, salvage therapy, salvage precarious relationship, salvation, beyond salvaging	打捞 抢救 营救 回收利用, 挽救疗法 补救治疗, 挽救岌岌可危的关系, 救恩 救世, 除了救助",
"sentiment, echoed this sentiment, sentiment analysis, to fan sentiment, dampened market sentiment, souring sentiment, opposite sentiment shortly afterwards	情绪 观点 意见, 附和了这一意见, 意见分析, 煽情, 降低, 减弱市场情绪, 情绪恶化, 不久之后相反的意见 opinion, persuasion, view, thought, nostalgic feeling or emotion",
"singular, singularity, existence of a stress singularity, The singularity loci and dexterity, singularity arises only formally, using the methods in singularity theory, conclusions for the singularity analysis of mechanism	单数 非凡突出 奇怪异常, 奇異 奇特 獨一 异常, 存在应力异常, 异常轨迹曲线和灵巧度, 异常的产生仅仅是形式上的, 利用异常理论方法, 异常分析机制的结论 remarkable, extraordinary, novel, wonder, exquisite",
"slate, slated, a clean slate, slated for 2018, slated to take place, start with a clean slate, blank slate with broad application	预定 确定 计划 石板 候选人名单 批评 安排 推举, 用石板瓦盖, 干净的石板 清白的历史, 预定2018, 预定举行, 重新开始, 广泛用途的空白石板",
"Spoil, spoils easily, Jedi spoilers, unruly spoilt kids, fight over the spoils, spoils of war, spoiler, spoiler candidate, spoiling for a class war	破坏 搞砸 溺爱 变坏 次品 奖品 战利品, 容易变质, 绝地武士破坏者, 任性的宠坏了的孩子, 争夺奖品, 战利品, 阻流板 选举中的搅局者, 搞砸的事人, 搞砸的候选人, 溺爱阶级战争 bungle, despoil, fluff, foul up, harry, loot, mess up, mismanage, muff, pilferage, pillage, plunder, screw up, prey upon, dote upon, prize, award, inferior",
"loyalty, stay loyal to, loyalists	忠诚, 对…保持忠诚, 效忠者 fealty, faith, devotion, allegiance, faithfulness, adherence, fidelity, trustiness",
"synopsis, Synoptic, synoptical, three-minute synopsis, provides a synopsis of her background	大纲 总结 提纲 提要 摘要 撮要 梗概 概括 概要 简介 纲目 纲要 纲领 要点 要素 轮廓, 概略的, 概要的, 三分钟概要, 提供了一个她的背景简介 compendium, diagrammatic, essentials, outline, schema, schematic, sketchy, summary",
"tavern, in the town’s tavern	酒馆, 在镇上的酒馆里",
"umbilical	脐带的 母系的",
"UUV	unmanned undersea vehicle",
"vat	大桶",
"venom, venomous, nonvenomous, envenoming, spreading venom, scorpion venom	毒液, 有毒的 刻薄 苛刻 刻毒, 无毒的, 使有毒 下毒 毒害, 散播毒液, 蝎毒 bitchy",
"manifest, manifestations, manifestly, manifestly failed, manifestations of extremism, clinical manifestations, manifest themselves in apocalyptic visions	显示 表明 明显的 显著的, 表现, 显然地, 显然失败了, 极端主义的表现, 临床表现, 显现他們在世界末日的景象 performance, expression, representation, display, show, clear, stark, apparent, obvious, distinct, glaring, sparkly, visibly, notable, significant, pronounce",
"vignettes	小插圖 简介短文",
"wean, wean off, attempt to wean the country off	使断奶 使断念 使放弃 使分离 戒断 戒瘾 断奶 逐渐停止, 试图让这个国家断绝关系 ablactate, detach the affections of",
"affirm that, reaffirm unity against terrorism, Affirmative, Affirmative Action, affirmative-action privileges, fallacy of affirming the consequent, special affirmative rights, on our affirm	肯定 确认 断言, 重申团结反对恐怖主义, 肯定的 赞成的 积极的, 反歧视行动 平权政策, 平权政策特权, 肯定结果的谬论, 特别肯定的权利, 我们保证 declare, to be certain, recognize, confirm on, positive, active, energetic",
"ascertaining, to ascertain	确定",
"methodology, methodological, tweaks to the design and methodology, methodological approach	方法学, 方法学的, 对设计和方法的调整, 研究方法 系统性方法",
"In particular, Particular Specification, not particularly original, particularly, particularly baffling, particularly interested in	特别地 尤其是, 具体的规范, 不特别是原始, 特别 尤其 异乎寻常地, 尤其令人困惑, 特别感兴趣",
"beggaring, The Beggars' Sect, a sly old beggar, Beggar Thy Neighbor, beggar-thy-neighbour	乞讨, 丐幫, 狡猾的老乞丐, 损人利己 以邻为壑 通过削弱邻国的经济来提升自己的经济地位",
"Electromagnetic Compatibility	电磁兼容性",
"address, shall be addressed, not addressed, set to address, address their differences, measures to fully address, Failure to address those challenges, addressed to me, Addressing leaders	称呼 书写 地址 发言 演说 向…说话, 要解决, 没有解决, 开始處理, 解决他们的分歧, 完全解决的措施, 未能应对这些挑战, 写给我, 向领导人讲话",
"setting, another setting, setting out, setting off, set alight, setting herself alight, record-setting, setting in motion, Setting aside, Settings cog, in any setting	环境 背景 级 设置, 另一个环境, 放样, 掀起 使爆炸, 点燃, 点燃自己, 创纪录, 启动 开始行動, 撇开, 设置齿轮, 在任何情况下",
"accord, peace accords, climate accord, national accord, covering climate accords, not accord with the facts, according to thy word, according to the contract provisions	协议 条约 符合 一致 自愿 给予待遇, 和平协议, 气候协议, 全国协议 条约, 覆盖气候协议, 不符合事实, 根据你的话, 根据合同规定",
"assured me, to reassure, self-assured, assure its people of sustenance, seem to quell or reassure those fuming on social media	向我保证, 再保证 使安心放心, 有自信的 胸有成竹, 保证人民的生计 食物, 似乎平息或安抚那些在社交媒体上冒烟的人",
"Statute, statutory, statute books, statutory requirement, statutory license, statutory minimum age at when become a mayor, Blocking Statute, statutorily required to be carried out	法令 法规 条例, 法典 法规汇编, 法定要求, 法定许可, 成为市长的法定最低年龄, 封锁令 禁制性法规, 法定要求执行 act, bill, law, order, ordinance, decretory, lawful",
"commissions, Out of commission for a little, commissioning warship, Commissioning Requirements, decommissioned, Decommissioned personnel, replace decommissioned ageing plants	佣金 手续费 委员会, 暂时没有佣金, 调试军舰, 调试要求, 退役; 退役人员, 更换退役老化设备",
"physics buff, physical conditions, very physical business, physical breach, physical effects, physical exertion, physical strength	物理爱好者, 物理条件, 非常实体的业务, 实物入侵, 物理效应 实物效果, 体力消耗, 体力",
"Phase, Phase Sequences, phase out, phase out plastic straws, phased out under the deal, part of the phased plan, phased plan	阶段 时期, 相位顺序, 淘汰 根除, 逐步淘汰塑料吸管, 根据协议淘汰 在协议下逐步退出, 分阶段计划的一部分, 分阶段计划",
"resign oneself to, promised to resign, resigned from cabinet, to resign in disgrace, retracted his resignation	依从 听任 甘受, 承诺辞职, 从内阁辞职, 丢脸地辞去职务, 收回他的辞呈 comply with, obey, listen to, heed, yield",
"relevant, relevative, relevance, as relevant, relevant side, remain relevant, more relevant results, stops relevant activities, relevant classics, irrelevance, exacerbate the growing irrelevance	相关的, 关联, 有关的 相关联的, 有关方面, 保持自身地位 价值, 更多的相关结果, 停止相关活动, 相关经典, 不相关 无关紧要 无关紧要的事物, 加剧日益增长的无关紧要的事物",
"code, COP Code of Practice, Both codes, security code, football codes, code violations, code of conduct, land-clearing codes, weaponise the tax code	密码 编码 道德准则 规则 守则 行为规范, 实务守则, 两种行为规范, 保安规则, 足球守则, 违反守则, 行为准则, 土地清理守则, 武器化税法",
"typified, Typically, typically obviate, typically three pronged, typically enough to hover, typically go down without a fight	典型化, 通常, 通常会避免, 通常三叉, 通常足以悬停, 通常没有战斗就停止 representative, model, prototypes, quintessence, characteristic, example, exemplary, classic",
"Associated, Associated Documents, a research associate, an associate dean, disassociates	联合的 有关联的, 相关文件, 研究合伙人, 副院长, 解除关联",
"Workmanship Requirements	工艺要求",
"Test Configuration	测试配置",
"bond, bond with their animals, bonded labour, held without bond, special bond, Earth bonding, baby bond 3D scanner, Bonded Warehouse, bonding, spend enough time bonding with them	债券 粘着 约定 团结 粘合剂 纽带 以…作保, 与他们的动物粘着, 干苦力活 蓄奴, 被捕后未被保释, 特别团结在一起, 接地焊接, 婴儿黏合三维扫描仪, 保税仓库, 增强 建立互信关系, 花足够的时间与他们粘着 agglutination, glueing, adhesion, combination, coupling, adhesive, couple, tie in, held in slavery, enslaved, enthralled in bondage",
"impede, Impedance Test, unimpeded, move unimpeded, impediment to meaning, strong impediment	阻碍 阻止, 阻抗测试, 畅通 无障碍的, 畅通无阻, 对意义的阻碍, 强大的障碍",
"conduct, conductor, illegal conduct, code of conduct, conducted raids, conducting career, outrageous conduct	进行 实施 指挥 带领 引导 行为 经营方式 乐队指挥 检票员, 非法行为, 行为守则, 实施劫掠, 开展事业 指揮事业, 暴行 lead through, manage, run, direct, going on, behavior, enforcement",
"whistleblower, whistle-stop trip, blew the whistle, dog whistle, dog-whistle votes	告密者 揭发者, 暂时停留的小站 小镇 暂时停留的旅行, 告发 揭发, 暗语, 狗哨投票",
"double talk	谎言 花言巧语",
"awkwardly, awkwardness, imitate awkwardly, awkward admission, in awkward positions, awkward, but possible to teach them skills	尴尬地, 尴尬, 东施效颦, 尴尬的承认, 在尴尬的位置, 尴尬 笨拙, 但可能教他们技能 clumsy, difficult, embarrassed, foolish, uncomfortable, distressed, shamefaced",
"rampage, vigilante rampaged, prompting police to quell the rampage	横冲直撞 狂暴乱闹 发怒暴怒 狂暴行为, 治安隊员横冲直撞, 促使警察平息暴乱 fury, rough house, anger, chafe at",
"groundless, hold ground, on the ground, groundbreaking, ground clutter, ground dispatcher, ground siege, stamping ground, thin on the ground, slumped to the ground, yet to get off the ground	毫无根据的, 坚守阵地, 在地上 当场, red-handed, 突破性的, 地面杂波, 地面调度员, 地面包围, 落脚处 常到的地方, 稀少的 寥寥无几, 倒在地上, 尚未开始",
"sanctions, sanctions against, sanctioned march, A lot will depend on the sanctions, veto any new sanctions, imposing unilateral sanctions, gives 2nd nod to counter-sanctions	制裁 处罚 认可 支持 批准 鼓励 约束, 批准的游行, 很多将取决于许可, 否决任何新的制裁, 强迫单边制裁, 第二次点头反击制裁",
"congressman, chambers of Congress, Congressm, congressional, report congressional votes, sense of the Congress, House Democrats, GOP Congressional leaders, Congress remained in session, Commons	国会议员, 国会议院, 国会 代表大会 会议 社交, 国会的, 报告国会投票, 国会想法, 国会民主党人 众议院民主党人, 共和党国会领袖, 国会依旧一直都在开会, 英国国会下院",
"lynchings, victim of lynching, innumerable lynching trees, amid a spate of mob lynchings	私刑, 私刑的受害者, 无数的私刑树, 在一群暴民的私刑中",
"impeachment, impeachment-crusading	弹劾, 弹劾十字军",
"ram, battering ram, political battering ram, rammed with people, rams, ram into, used as rams	撞击 塞进 挤进 猛撞 反复灌输, 攻城锤 攻城槌, 政治攻城锤, 挤满人, 公羊 白羊座, 猛撞, 用作攻城槌",
"defacing, defaced with	丑化",
"phobia, xenophobia, xenophobic tendencies, profuse tearing and photophobia, hydrophobic, transphobic, fat-phobic, transphobia, xenophobic	恐惧症, 仇外, 仇外倾向, 落泪不止和畏光, 狂犬病的 畏水的, 变性者恐惧, 肥胖恐惧, 跨性别恐惧, 恐惧外国人的",
"graffiti, graffitied	涂鸦 doodle",
"siege, siege-like, ground siege, lay siege, besieged city, besieged by government forces, state of siege	围攻, 像围攻一样, 地面包围, 围攻 围困 围城 不断袭击 长期努力, 被围困的城市, 被政府军包围, 戒严状态",
"avatars	化身",
"pale, beyond the pale, beyond the pale of humanity, live beyond the 'pale of settlement', hypothetical vulnerabilities pale next to	围篱 范围 脸色苍白 浅颜色 暗淡的 微弱的 逊色的 相形见绌, 在…范围之外 不可接受, 人类范围以外, 住在 “定居区” 外, 假设漏洞比不上",
"relativising	相对化",
"erratic, erratically, remained highly erratic ever since	行为古怪 反复无常 飘忽不定的 不规则的, 不规律地, 自始至终都依然很不稳定 unpredictably",
"smashes, smashed windows, smashing in penalty, smashed homes, smash hit, get smashed flat by rock slides, the sun has been smashing me	捣毁 打碎 被砸 大醉 猛烈撞击 击穿, 砸碎窗户, 罚球, 砸了家, 扣杀命中, 被岩崩砸扁, 太阳一直在砸我 breaking, shattering, crash",
"Confed, Confederation, confederate, tribal confederacy, Confederate monuments, Confederations Cup	联邦, 联合的, 部落联盟, 邦联纪念碑, 国际联合会杯赛 federal, associated, in league, amalgamated, allied",
"erupts, erupt in flames, diplomatic row erupted, recent eruption of the debate, eruption block recovery efforts	爆发, 爆发出的火焰, 外交瞎闹爆发了, 最近爆发的辩论, 大喷发阻碍了恢复努力 break out, explode, burst out",
"austere, austerity, austere offerings, comparatively austere life, The room was austere, a distant austere man, war and austerity, anti-austerity, Austerity had a crippling impact, his austere worldview	严峻的 严肃的 简朴的 苦行的 无装饰的 一丝不苟的, 紧缩 苦行 严厉 简朴 朴素 节衣缩食, 严厉的奉献, 相对而言简朴生活, 这个房间很简朴, 难以接近的严肃的人, 战争和紧缩, 反緊縮, 紧缩政策产生了严重影响, 他严峻的世界观 severe, naked",
"Orthodox, orthodoxy, Eastern Orthodox, orthodox campaign, Less orthodox theories, broke from prevailing orthodoxies, unorthodox working life, The orthodoxy says that	正统的 保守的, 东正教, 正统的竞选运动, 不太正统的理论, 抛开盛行的正统观念, 非正统的工作生活, 传统观点认为 legitimism, backward-looking, conservative, old-fashioned, old-line, ossified",
"premier, premiere, premier owner, premiered Wednesday, premiership	第一次 第一的 最初的 总理 首相, 首映, 最初的主人 最初的 首位的, 周三首次公演, 首相职位(或任期) 总理职位(或任期) first-time, chairman, president",
"At no time, in no time flat, whip up a meal in no time, at the time, big time, lose money big time, develops over time, doing shit all the time, flourished at a time	在任何时候 决不 从不, 立刻 马上, 立刻很快做出一顿饭菜, 当时 在那时 在那段时间, 大范围地 很大程度地, 大亏本, 随着时间的发展, 一直在拉屎, 兴盛一时",
"breath, bated breath, breathtaking, It's breathtaking, uplifting rescue, breath of fresh air, breathless reports, In the other breath	呼吸 气息 一丝 迹象 一瞬间, 屏息以待, 使人透不过气来的 惊人的, 这是激动人心的, 令人振奋的救援, 呼吸新鲜空气; 使人耳目一新, 带来新鲜感, 氣喘吁吁的, 上氣不接下氣的的报道, 另一瞬间",
"emir, emirates	埃米尔 对穆斯林统治者的尊称, 酋长 埃米尔的地位或国家、权力、土地 酋长国",
"reel, reeling, reel under the surge, reeling from a series of construction scandals, Showreel, reels of shame	卷轴 失去平衡, 蹒跚 摇摆 踉跄 感到震惊, 激增下感到震惊, 感到震惊一系列建筑丑闻, 作品集, 耻辱卷轴 bobbin, spool, stagger, stagger, keel, lurch, swag, careen, spin, whirl, gyrate",
"populous, most populous city, most populous markets	人口稠密的, 人口最多的城市, 人口最多的市场",
"Genesis, the genesis of which, neurogenesis, pathogenesis, Ketogenesis	起源 创始, 它的起源, 神经形成 神经生成, 发病机理 发病原, 生酮作用 刺激酮体生成",
"trio	三重奏",
"ascend, ascendant, ascendancy, ascendance, ascending to higher office, ascension, ascension of a reality star, ascension to the White House, Unconquered ascent, death-defying pioneering ascents, a pretty clear ascendency	上升, 上升的 越来越大, 支配地位 优势 高峰, 崛起 优越 权势, 上升到更高的职位, 上升 升高, 现实之星的提升, 升任白宫, 未征服的攀登, 无畏的开拓性攀登, 非常明显的优势 rising, climbing, upward, raise, dominance, control, dominating",
];

