// Geography Quiz Data
window.quizData = [
 "Tempo	速度术语 指示音乐的快慢，通常位于乐谱开头。",
 "Grave	Very slow and solemn - 庄板（极慢、沉重）速度",
 "Largo	Very slow and broad - 广板（很慢、宽广）速度",
 "Lento	Slow - 慢板速度",
 "Adagio	Slow, at ease - 柔板（从容、舒缓）速度",
 "Andante	At a walking pace - 行板（如行走速度）速度",
 "Moderato	Moderately - 中板速度",
 "Allegro	Fast, cheerful - 快板（活泼、快速）速度",
 "Vivace	Lively and fast - 活板（快速有活力）速度",
 "Presto	Very fast - 急板（极快）速度",
 "Prestissimo	As fast as possible - 最急板速度",
 "issimo	非常（如 Allegrissimo 极快的）速度",
 "etto	稍、略微（如 Allegretto 小快板，比快板略慢）速度",
 "Accelerando (accel.)	逐渐加快速度",
 "Ritardando (rit.) / Rallentando (rall.)	逐渐减慢速度",
 "A tempo	恢复原速",
"音乐记谱术语:	主要源自意大利语，已成为国际通用音乐语言",
 "Staff & Notation Systems	谱表与记谱系统",
 "Staff / Stave	Staff 五线谱 五条平行线",
 "Clef	Clef 谱号 确定音高位置",
 "Treble Clef	Treble Clef / G Clef 高音谱号 𝄞",
 "Bass Clef	Bass Clef / F Clef 低音谱号 𝄢",
 "Alto Clef	Alto Clef / C Clef 中音谱号 中提琴常用",
 "Tenor Clef	Tenor Clef / C Clef 次中音谱号 大提琴/巴松高音区",
 "Grand Staff	Grand Staff 大谱表 钢琴谱高低音谱表组合",
 "Ledger Line	Ledger Line 加线 五线谱外的短横线",
 "Bar / Measure	Bar (UK), Measure (US) 小节 两条小节线之间的部分",
 "Bar Line	Bar Line 小节线 分隔小节的垂直线",
 "Double Bar Line	Double Bar Line 双小节线 乐段结束 𝄂",
 "Final Bar Line	Final Bar Line 终止线 乐曲结束 𝄃",
 "Notes & Rests	音符与休止符",
 "最长	Breve, Double Whole Note, 𝅜 休止符𝄺",
 "4拍	Semibreve, Whole Note, 𝅝 休止符𝄻",
 "2拍	Minim, Half Note, 𝅗𝅥 休止符𝄼",
 "1拍	Crotchet, Quarter Note, ♩ 休止符𝄽",
 "1/2拍	Quaver, Eighth Note, ♪ 休止符𝄾",
 "1/4拍	Semiquaver, Sixteenth Note, ♬ 休止符𝄿",
 "1/8拍	Demisemiquaver, 32nd Note, 三旗 休止符𝅀",
 "1/16拍	Hemidemisemiquaver, 64th Note, 四旗 休止符𝅁",
 "Dotted Note	附点音符（时值增加1/2）",
 "Tie	连音线（连接相同音高，时值相加）",
 "Slur	圆滑线（连接不同音高，连奏）",
 "Beam	符杠（连接八分、十六分音符的横线）",
 "Pitch & Key Signatures	音高与调号",
 "Sharp	升号 (♯) 升高半音",
 "Flat	降号 (♭) 降低半音",
 "Natural	还原号 (♮) 取消升降",
 "Double Sharp	重升号 (×) 升高全音",
 "Double Flat	重降号 (♭♭) 降低全音",
 "Key Signature	调号 谱号后的升降号",
 "Accidental	临时记号 改变音高的符号",
 "Enharmonic	等音 音高相同，记谱不同",
 "Time Signature	拍号, 4/4, 3/4, 6/8",
 "Common Time	普通拍子, C = 4/4",
 "Cut Time / Alla Breve	二二拍子, ¢ = 2/2",
 "Beat	拍子, 基本时间单位",
 "Downbeat	强拍, 小节第一拍",
 "Upbeat / Anacrusis	弱起拍, 小节开始前的拍子",
 "Syncopation	切分音, 强调弱拍的节奏",
 "Triplet	三连音, 三等分标准时值",
 "Solo	独奏, 单个演奏者",
 "Tutti	全奏, 全体一起演奏",
 "Divisi	分奏, 声部分开演奏不同音",
 "Unison	齐奏, 所有声部奏相同音",
 "Senza sordino	除去弱音器, 弦乐/铜管指示",
 "Con sordino	加弱音器, 弦乐/铜管指示",
 "Pizzicato	拨奏, 弦乐指示",
 "Arco	拉奏, 弦乐恢复用弓",
 "Dynamics	力度术语 指示音乐的强弱",
 "ppp	Pianississimo (as soft as possible) 极弱力度",
 "pp	Pianissimo (very soft) 很弱力度",
 "p	Piano (soft) 弱力度",
 "mp	Mezzo-piano (moderately soft) 中弱力度",
 "mf	Mezzo-forte (moderately loud) 中强力度",
 "f	Forte (loud) 强力度",
 "ff	Fortissimo (very loud) 很强力度",
 "fff	Fortississimo (as loud as possible) 极强力度",
 "cresc. 或 <	Crescendo (gradually louder) 渐强力度",
 "dim. 或 >	Diminuendo (gradually softer) 渐弱力度",
 "sfz	Sforzando (sudden strong accent) 突强（一个音）力度",
 "Expression	表情与风格术语",
 "Dolce	Sweetly 甜美地、柔和地风格",
 "Cantabile	In a singing style 如歌地风格",
 "Espressivo (espr.)	Expressively 富有表情地风格",
 "Legato	Smoothly connected 连贯地、圆滑地风格",
 "Staccato (stacc.)	Detached, short 断奏、跳音风格",
 "Marcato	Marked, accented 强调的、突出的风格",
 "Tenuto (ten.)	Held, sustained 保持（时值饱满）风格",
 "Sostenuto	Sustained, prolonged 持续、绵延地风格",
 "Agitato	Agitated, excited 激动地、不安地风格",
 "Maestoso	Majestic 庄严地、宏伟地风格",
 "Tranquillo	Tranquil, calm 安静地、平静地风格",
 "Scherzando	Playful, joking 诙谐地、嬉戏地风格",
 "Articulation & Technique	演奏技法术语",
 "Arco	With the bow (弦乐) 用弓拉奏演奏技法",
 "Pizzicato (pizz.)	Plucked (弦乐) 拨奏演奏技法",
 "Glissando (gliss.)	Sliding between notes 滑奏、刮奏演奏技法",
 "Tremolo	Rapid repetition of a note 颤音（快速反复）演奏技法",
 "Trill (tr)	Rapid alternation between two notes 颤音（两个音交替）演奏技法",
 "Vibrato	Slight pitch variation for warmth 揉弦、振音演奏技法",
 "Con sordino	With mute 加弱音器演奏技法",
 "Senze sordino	Without mute 除去弱音器演奏技法",
 "Form & Structure	曲式与结构术语",
 "Opus (Op.)	Work (used to catalogue a composer\'s works) 作品编号",
 "Movement (Mov.)	A self-contained part of a larger work 乐章",
 "Cadenza	A virtuosic solo passage 华彩乐段（常即兴）",
 "Coda	A concluding section 尾声",
 "Da Capo (D.C.)	From the beginning 从头反复",
 "Dal Segno (D.S.)	From the sign (𝄋) 从记号处反复",
 "Fine	The end 结束",
 "Attacca	Go on without pause 紧接下一乐章",
 "Genres / Forms	常见曲体裁",
 "Sonata	A piece for solo instrument (or small ensemble), usually in multiple movements 奏鸣曲",
 "Symphony	A large orchestral work, usually in four movements 交响曲",
 "Concerto	A work for soloist(s) and orchestra 协奏曲",
 "Etude	Study (focuses on a particular technical challenge) 练习曲",
 "Nocturne	Night piece (lyrical, dreamy character) 夜曲",
 "Prelude	Introductory piece, or a short standalone work 前奏曲",
 "Fugue	A complex contrapuntal composition with a recurring subject 赋格",
 "A cappella	Without instrumental accompaniment	无伴奏合唱",
 "Divisi (div.)	Divided (弦乐声部拆开演奏不同声部)	分部演奏",
 "Tutti	All (整个乐队一起演奏)	全奏、合奏",
 "Solo	Alone (单个演奏者)	独奏/独唱",
 "Ad libitum (ad lib.)	At the performer\'s liberty	自由处理（速度、装饰等）",
 "Ossia	Or, alternative passage	替代指法或段落",
 "Poco a poco	Little by little	逐渐地、一点点地",
 "Chord	和弦是三个或三个以上不同音高的音符同时或依次发声的组合，是和声学的基本组成单位。",
 "Triads	三和弦 最基本的和弦，由三个音符按三度叠置构成",
 "Seventh Chords	七和弦 在三和弦基础上加七度音",
 "和弦标记法 流行/爵士标记法 流行音乐常见	C C大三和弦 (C major), Cm C小三和弦 (C minor), C7 C属七和弦 (C dominant 7th)",
 ];